### ISSUE TITLE
7.116.2: can't install cli with npm

### ISSUE THREAD

**Issue by alanjaouen** [forcedotcom/cli#1174]
### Summary

When I upgraded my npm project dependencies from "sfdx-cli": "7.114.0" to "sfdx-cli": "7.116.2", I'm not able to run "npm install" anymore

### Steps To Reproduce:

create a package.json file with content 
```
{
  "dependencies": {
    "sfdx-cli": "7.116.2"
  }
}

```
and run npm install

### Expected result

npm should install my dependencies

### Actual result

i get the following error, seem that an additional `node_modules/@salesforce` si in the path
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /opt/rundeck/git_repositories/Salesforce/node_modules/sfdx-cli/node_modules/@salesforce/cli/bin/run
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/opt/rundeck/git_repositories/Salesforce/node_modules/sfdx-cli/node_modules/@salesforce/cli/bin/run'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

### System Information

sfdx is not installed

### Additional information

It's works like a charm on a windows PC, I have issues on debian linux 

```
> uname -a
Linux scaledeck-scale-1c-0 4.19.0-11-cloud-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux
```

**Comment by javierCTL** [comment]
We're experiencing the same issue, we are not able to successfully `npm install`. This is happening with version `7.114.0` and also with `7.116.2`

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/Javi/salesforce/node_modules/sfdx-cli/node_modules/@salesforce/cli/bin/run
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/Javi/salesforce/node_modules/sfdx-cli/node_modules/@salesforce/cli/bin/run'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by mshanemc** [comment]
Can you try also including `@salesforce/cli` as a dependency?  I think this is related to how we included the new `sf` cli

**Comment by javierCTL** [comment]
Hi @mshanemc, thank you for your answer. I'm afraid we get the same error if `@salesforce/cli` is included.

```
{
  "dependencies": {
    "sfdx-cli": "7.116.2",
    "@salesforce/cli": "0.0.38"
  }
}
```

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/Javi/salesforce/node_modules/sfdx-cli/node_modules/@salesforce/cli/bin/run
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/Javi/salesforce/node_modules/sfdx-cli/node_modules/@salesforce/cli/bin/run'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

Looking at the route, it seems **npm** it's expecting to find `@salesforce/cli` within `sfdx-cli`

**Comment by alanjaouen** [comment]
Hi @mshanemc, I confirm that adding @salesforce/cli as a dependency do not solve the issue

while having a look at npm logs, i found that the issue is caused by a chmod, so i looked at the code and I found in the sfdx-cli repo that a new script was added 2 weeks ago with some hardcoded path: 
https://github.com/salesforcecli/sfdx-cli/blob/main/scripts/include-sf.js

maybe this is related to our issue

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9875023](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000005a2LVYAY/view)

**Comment by mshanemc** [comment]
I've made the `sf` cli folks aware of this.  Out of curiosity, is it specific to npm or yarn, too?
@javierCTL what os/version are you seeing the error?

**Comment by javierCTL** [comment]
Hey @mshanemc, I've just tried and seems to be specific to npm. We're seeing the error in this os:
- Ubuntu 20.04
- macOS Big Sur 11.5.2
- Amazon Linux 2

**Comment by mshanemc** [comment]
We found a way to replicate it on mac.  It *should* be fixed in the rc-release from yesterday (7.118.1).  Can you give it a try?

**Comment by javierCTL** [comment]
Hi @mshanemc, we've tested it and everything works as expected. Thanks a lot for all your help with this issue.

**Comment by rshircliff** [comment]
It appears this is still an issue when declaring the dependency using this syntax "^7.0.0". Can we reopen this issue or do I need to create a new one?
