### ISSUE TITLE
Significant increase in memory / RAM consumption after version 7.111.6 when running force:source:retrieve with StaticResource

### ISSUE THREAD

**Issue by nathanfranklinau** [forcedotcom/cli#1348]
I've noticed a significant increase in RAM consumption after version 7.111.6 when running force:source:retrieve with StaticResource. 

I have used pmap cli command to profile the memory consumption for the node instance running the retrieve command.

To test this, I attempted a retrieve on a single compressed StaticResource (4.3mb) which contained around 2k files. In 7.111.6, the retrieve this StaticResource, I observed total memory consumption of around 1.1gb. After 7.111.6, I observed total memory consumption of around 4.3gb!

I haven't tested this in detail, however, it seems that this might be limited to zipped static resources.

Has anyone else experienced this? If so, does anyone have a workaround? Currently retrieving all StaticResources kills my docker container since it's exceeding the maximum configured RAM which I'd prefer not to change.

**Comment by mshanemc** [comment]
Let us known if it's still happening on more recent versions, and if so, whether you can describe the contents of your static resource (# of files, what type of files they are, what the directory structure is inside of it) so we could replicate.

7.111 is one of the first releases that used the new deploy/retrieve library and we've made some changes to zip operations after that that might help.

**Comment by nathanfranklinau** [comment]
Hey mate

Yes it's been happening since version 7.112.0. I've tested different versions between 7.112.0 up to 7.132.0 and each test produced the same result.

The static resource is an old SLDS asset v2.0.3. It's 4.3mb compressed and contains just over 2k files.

My workaround is to retrieve StaticResource's using Metadata API (not sfdx), and then run force:mdapi:convert which seems to convert the StaticResource's without any issue.

**Comment by maggiben** [comment]
Hi Nathan, can you create an slds static resource repo for us to try reproduce the error ?

**Comment by nathanfranklinau** [comment]
Hey, this one should do it
https://github.com/nathanfranklinau/StaticResourceMemoryTest

**Comment by maggiben** [comment]
Hi @nathanfranklinau I tried your deployment and I recorded the RAM usage thought the process 90% of the time it idle at about 165Mb, then right about the end it spiked to about 3.6Gb, so certainly it's quite a lot for just a few mb of files, can't really tell you exactly where the problem is but Im going to open a new bug.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10417338](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000eNTvAYAW/view)

**Comment by cristiand391** [comment]
This was fixed in `sfdx-cli@7.139.0`, release notes:
https://github.com/forcedotcom/cli/tree/main/releasenotes/sfdx#71390-feb-24-2022-stable

Update instructions:
https://developer.salesforce.com/docs/atlas.en-us.212.0.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm

Thanks!

**Comment by nathanfranklinau** [comment]
Hey! I've noticed that in the latest version of sfdx, this is still a problem. While using force:mdapi:convert with static resources, the memory of my docker containers hits 8GB and then dies.

**Comment by nathanfranklinau** [comment]
I've uploaded a screencast which shows the memory usage when running force:mdapi:convert on a package with 2 static resources only:
https://drive.google.com/file/d/16B1ShbMiZfqAHFZ7FrYxekhHhQ8pAAO_/view

It shows an increase up 6.9 GB in the screen, but the overall container memory usage hit it's threshold of 7.75GB before it died.

The file itself is an old version of SLDS:
# Lightning Design System
# Version: v0.8.0

I've uploaded the static resource here: https://drive.google.com/file/d/1rL6eBun-zAch6KcWcOR4IoMytbgmxrr3/view?usp=sharing

Hoping this helps diagnose the issue further
