### ISSUE TITLE
Failing to delete scratch orgs.

### ISSUE THREAD

**Issue by sfrycertinia** [forcedotcom/cli#1423]
### Summary

We are seeing some instances of scratch orgs failing to delete with the following message.

```
Unable to associate this scratch org with a DevHub
```

### Steps To Reproduce:

Create a scratch org.

Associate it with a local environment using JWT auth.

Delete the scratch org.

```
sfdx force:org:delete -p -u <username>
```

### Expected result

Scratch org is deleted.

### Actual result

Scratch org remains active.

### System Information

{
        "cliVersion": "sfdx-cli/7.136.2",
        "architecture": "linux-x64",
        "nodeVersion": "node-v14.15.4",
        "pluginVersions": [
                "@ffdev/ffdx 3.6.3 (3.6.3)",
                "@ffdev/ffplay 1.1.3 (1.1.3)",
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.8.0 (core)",
                "auth 1.8.1 (core)",
                "config 1.3.15 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.2 (core)",
                "info 1.2.0 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.1 (core)",
                "salesforce-alm 53.7.6 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.136.2 (core)",
                "source 1.8.9 (core)",
                "telemetry 1.4.0 (core)",
                "templates 53.3.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Linux 5.10.76-linuxkit"
}

**Comment by jeffhube** [comment]
We are seeing the same issue.
```
sfdx force:auth:jwt:grant -r https://test.salesforce.com -u <scratchorgusername> -a <alias> -f <jwtkeyfile> -i <clientid>
```
And then both
```
sfdx force:org:delete -u <alias> -p
```
and
```
sfdx force:org:delete -u <alias> -v <devhubusername> -p
```
result in
```
ERROR running force:org:delete:  Unable to associate this scratch org with a DevHub
```
This is on version `7.139.0`, I believe it was working as expected on `7.107.0`
```
{
        "cliVersion": "sfdx-cli/7.139.0",
        "architecture": "linux-x64",
        "nodeVersion": "node-v14.18.2",
        "pluginVersions": [
                "@nimbleams/sfdx-nimbleams 1.3.0",
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.1 (core)",
                "apex 0.9.0 (core)",
                "auth 1.8.1 (core)",
                "community 1.1.4 (core)",
                "config 1.3.19 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.9 (core)",
                "generator 1.2.2 (core)",
                "info 1.2.1 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.1 (core)",
                "salesforce-alm 53.10.2 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.139.0 (core)",
                "sfpowerkit 3.3.4",
                "source 1.8.12 (core)",
                "telemetry 1.4.0 (core)",
                "templates 53.6.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.1 (core)"
        ],
        "osVersion": "Linux 4.4.0-1128-aws"
}
```

**Comment by cristiand391** [comment]
Hi @sfryffdc @jeffhube 
I've been trying to replicate this, authenticated to my devhub using JWT and created a scratch org and I'm able to delete it.

The error is coming from here: https://github.com/forcedotcom/sfdx-core/blob/45b11c526f9bb461a61c145cf9ae6160d8b61afa/src/org.ts#L710

So `sfdx-core` fails to find the dev hub, [this method](https://github.com/forcedotcom/sfdx-core/blob/45b11c526f9bb461a61c145cf9ae6160d8b61afa/src/org.ts#L331) relies on the local auth file to determine if the org is a devhub or not. Are you able to see the auth file in your `~/.sfdx` folder? 

It should be a json file like `name@test.org.json` and should have:
```json
  "isDevHub": true
```

**Comment by sfrycertinia** [comment]
@cristiand391 when we authenticate with the DevHub using 

```bash
sfdx force:auth:jwt:grant \
     --setalias DevHub \
     --username <redacted> \
     --jwtkeyfile <redacted> \
     --clientid <redacted>\
     --instanceurl https://<my domain>.my.salesforce.com \
     --setdefaultdevhubusername
```

Then the file in ~/.sfdx directory does not have isDevHub in it. What are we doing wrong?

Thanks

**Comment by jeffhube** [comment]
@cristiand391

In my `~/.sfdx` folder, the contents of file for the devhub are:
```
{
  "username": "DEVHUBUSERNAME",
  "accessToken": "****",
  "loginUrl": "https://login.salesforce.com",
  "privateKey": "****",
  "clientId": "****",
  "instanceUrl": "https://****.my.salesforce.com",
  "instanceApiVersion": "54.0",
  "instanceApiVersionLastRetrieved": "3/4/2022, 2:51:37 PM",
  "isDevHub": true
}
```
And the contents of the file for scratch org are:
```
{
  "username": "test-****@example.com",
  "accessToken": "****",
  "orgId": "****",
  "loginUrl": "https://test.salesforce.com/",
  "privateKey": "****",
  "clientId": "****",
  "instanceUrl": "https://****.cs92.my.salesforce.com",
  "instanceApiVersion": "54.0",
  "instanceApiVersionLastRetrieved": "3/4/2022, 2:52:13 PM",
  "isDevHub": false
}
```

I think the issue might be related to this line: https://github.com/forcedotcom/sfdx-core/blob/45b11c526f9bb461a61c145cf9ae6160d8b61afa/src/org.ts#L318 . There is no `devHubUsername` property in the scratch org file, but I do see it for scratch orgs that I create locally and can delete successfully.

I think the issue might also be related to creating the scratch org on one machine and authorizing it on another. I can reproduce the issue with the following steps on two machines:

**On the first machine:**
```
sfdx force:project:create -n tempsfdxproject
cd tempsfdxproject
sfdx force:auth:jwt:grant -u DEVHUBUSERNAME -d -f **** -i ****
sfdx force:org:create -f config/project-scratch-def.json
```

**On the second machine:**
**NOTE:** You may need to wait some time after scratch org creation for the login to propagate, or change `https://test.salesforce.com` to the scratch org's instance url (ex. `https://CS217.salesforce.com`). Otherwise you will get an error:
`ERROR running auth:jwt:grant:  We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: Error authenticating with JWT config due to: user hasn't approved this consumer`
```
sfdx force:auth:jwt:grant -u DEVHUBUSERNAME -d -f **** -i ****
sfdx force:auth:jwt:grant -r https://test.salesforce.com -u SCRATCHORGUSERNAME -a ALIAS -f **** -i ****
sfdx force:org:delete -u ALIAS -p
```

I did attempt to repro it on one machine by removing the org json file from `~/.sfdx`, but that was not successful. When I reauthorized the scratch org, the json file contained the `devHubUsername` property and I was able to succesfully delete it.

**Comment by sfrycertinia** [comment]
@jeffhube @cristiand391 Jeff's repro, is exactly the scenario we have. When we authenticate with the devhub on the second machine we do not get isDevHub true.

**Comment by cristiand391** [comment]
@jeffhube @sfryffdc thanks for the repro steps!

I've tried this 3 times with different containers:

1. Auth to my devhub using jwt on my local machine
2. Create scratch org `org-test1` on my local machine
3. Run a docker container, then auth to the same devhub using jwt, same with scratch org `org-test1`
4. Check that devhub file in `~/.sfdx` contains `"isDevHub": true` ✅ 
5. Check that scratch org file in `~/.sfdx` contains `"devHubUsername": "admin@integrationtesthub.org"` ✅ 
6. Run `sfdx force:org:delete -u org-test1`, deletes the scratch org ✅ 
7. Run `sfdx force:org:list` on my local machine, `org-test1` doesn't show up ✅ 

We haven't changed the logic that handles this in `sfdx-core`/`plugin-auth` in the last weeks.

Could both of you run again the commands with DEBUG=*? 
You should be able to see this msg on the log when trying to auth the scratch org with `auth:jwt:grant`:
https://github.com/salesforcecli/plugin-auth/blob/92c202d16767df92878bfcf2ba23f27d52e5259e/src/common.ts#L92

**Comment by sfrycertinia** [comment]
@cristiand391 I'd rather not post a verbose log with who knows what in it on here...

I have run the scenario again, what I don't understand is why doesn't the file in ~/.sfdx for my auth with the DevHub say isDevHub true? Can you explain why that might be?

Thanks for your work on this.

**Comment by jeffhube** [comment]
@cristiand391 @sfryffdc

The issue seems to be that the devhub is not marked as a devhub when it is initially authorized.

If I run `sfdx force:auth:jwt:grant -u DEVHUBUSERNAME -d -f **** -i ****` and then examine the `~/.sfdx/DEBHUBUSERNAME.json` file, there is no `isDevHub` property. If I run `sfdx force:org:list` and examine the file again, then it now contains `"isDevHub": true`.

So when authorizing the scratch org when that `isDevHub` property is missing, the relevant output I get is
```
sfdx:Common DEBUG found 0 DevHubs
```
If I run `sfdx force:org:list` before authorizing the scratch org, then I get
```
sfdx:Common DEBUG found 1 DevHubs
sfdx:Common DEBUG found orgId 00D*************** in devhub ****
sfdx:Common DEBUG set **** as devhub for scratch org ****
```
And then I can delete the scratch org successfully.

I was on sfdx version `7.107.0` before upgrading to version `7.139.0`, so the cause could be rather old.

**Comment by sfrycertinia** [comment]
@jeffhube nice! Now I can add this to my pipeline! Thanks (I have confirmed that I see this behaviour too)

I had noticed that something I did, ended up adding it but hadn't nailed it down.

@cristiand391 would be nice if this happens when authorising a scratch org using these credentials, as I don't really want to update hundreds of CI pipelines!

**Comment by sfrycertinia** [comment]
It seems I can do this before authorising the scratch org so I could add to my CI agent startup, after it does the auth to the dev hub.

**Comment by cristiand391** [comment]
@sfryffdc @jeffhube nice catch! I was able to reproduce it.

With `-d/--setdefaultdevhubusername`, the username is set as the default devhub globally (sfdx config:list) but the `isDevHub` property isn't set in the auth file.

I think I ran `force:org:list` after auth'd to the scratch org in the container to confirm that it was there, so that's probably why I didn't run into this scenario yesterday.

I'll log a new WI for this, thank you all for testing and reporting!

**Comment by cristiand391** [comment]
@sfryffdc @jeffhube this was fixed in `plugin-auth@1.8.2` which is included in our current latest-rc and will be promoted to latest next Thursday 👍🏼

**Comment by shetzel** [comment]
The fix for this issue is now in the latest production release of the CLI, 7.145.0.  Thanks for your patience!

**Comment by bdovh** [comment]
We still have this issue in version SFDX Version: sfdx-cli/7.146.1 linux-x64 node-v16.14.2

**Comment by cristiand391** [comment]
Hey @bdovh are you able to consistently reproduce the issue with the latest version?
At which step do you find sfdx missing devhubs?

**Comment by bdovh** [comment]
I think I had the following steps.

1. Authorize the scratch org.
2. Authorize the dev hub.
3. Try to delete this scratch org.
=> Error

**Comment by bdovh** [comment]
It seems to work when I swap step 1 and 2
