### ISSUE TITLE
Package version list command resulting in col.split error

### ISSUE THREAD

**Issue by richsabel** [forcedotcom/cli#1569]
### Summary

CLI release candidate version 7.155.0-d289574
Cannot produce concise package version output

### Steps To Reproduce:

Execute package version list command for concise output

`sfdx force:package:version:list -p PACKAGE_ALIAS -v DEVHUB --concise`

### Expected result

A concise package version list

e.g.
0Ho4Lx 3.12.0.1  04t4Lx             false
0Ho4Lx 3.12.0.2  04t4Lx             true
0Ho4Lx 3.13.0.1  04t4Lx             false
0Ho4Lx 3.14.0.1  04t4Lx             false
0Ho4Lx 3.14.1.1  04t4Lx             true

### Actual result

`ERROR running force:package:version:list:  col.split is not a function`

**Comment by WillieRuemmele** [comment]
I was able to reproduce on `7.155.0` with `salesforce-alm 54.5.0 (core)`

**Comment by jorgjanke** [comment]
Also failing here with 7.155.1 (June 16, 2022) [stable]
`ERROR running force:package1:version:list:  col.split is not a function `

**Comment by shetzel** [comment]
This is now fixed in the latest CLI.

**Comment by timthesinner** [comment]
@shetzel I am still seeing this error using `sfdx-cli/7.157.0 darwin-x64 node-v16.15.1`

**Comment by WillieRuemmele** [comment]
what's the output of `sfdx plugins --core`

**Comment by jorgjanke** [comment]
Same here - still see the col.split error with: 
```
sfdx version
sfdx-cli/7.157.0 darwin-x64 node-v16.15.1

sfdx plugins --core
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.3.1 (core)
@oclif/plugin-not-found 1.2.6 (core)
@oclif/plugin-plugins 1.10.11 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.4 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 2.1.0 (core)
apex 0.13.0 (core)
auth 2.2.0 (core)
community 2.0.0 (core)
config 1.4.12 (core)
custom-metadata 2.0.0 (core)
data 2.0.4 (core)
generator 2.0.1 (core)
info 2.0.1 (core)
isvte-sfdx-plugin 1.1.16
limits 2.0.1 (core)
org 1.13.2 (core)
salesforce-alm 54.6.1 (core)
schema 2.1.1 (core)
sfdx-cli 7.157.0 (core)
signups 1.2.0 (core)
source 2.0.3 (core)
telemetry 2.0.0 (core)
templates 55.0.0 (core)
trust 2.0.0 (core)
user 2.1.0 (core)

```

**Comment by cristiand391** [comment]
A fix for this was included in our latest-rc (7.158.1), please let us know if it works for you all, thanks!

**Comment by shillem** [comment]
Works for me!
