### ISSUE TITLE
general issues with node 18.16.0

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#2125]
We've got a cluster of issues where problems are related to nodejs 18.16.0.  This is the worst kind of bug, where it exits successfully but does not do what it was told.

https://github.com/forcedotcom/cli/issues/2116
https://github.com/forcedotcom/cli/issues/2119
https://github.com/forcedotcom/cli/issues/2121
https://github.com/forcedotcom/cli/issues/2092

### What's happening

the source conversion process (taking local source format and converting it the metadata API's format) is not working correctly, particularly around Static Resources (there may be other ways it's failing, but this is the one we can prove)

This not only happens for `source:convert`, but also all deployments from source (`push`, `source:deploy`, `project deploy` when not using mdapi format) and package version creation where your source gets converted and zipped up to send the packaging API.

### What should I do?
  
If you install via `npm` and you're in an environment where you manage your own node version, don't use node 18.16.0.  We've had success on the previous, fairly recent versions 18.14.2 and 18.15.0

If you're using our bundled node (tarballs/installers), you have good options.

1. Use 7.200.7 (`stable-rc | latest-rc` since May 11).  It includes `node 18.15.0
`.  
- You can say `sfdx update`
- You can check your version by running `sfdx version`
2. go back to to the 7.198 release, or earlier, which uses the previous node version.  Those instructions are here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_olderversions
   - `sfdx update --version 7.198.6`

**Comment by bdovh** [comment]
Is this possible to override github action node installed?

Should we just try to run the following set of commands:

```
sfdx update --version 7.200.7
sfdx update stable-rc
sfdx version
sfdx update --version 7.198.6
```
???

**Comment by bdovh** [comment]
But I have the following commands before:

```
node --version
npm install -g sfdx-cli@7.194.1
```

should I just merge them?

**Comment by bdovh** [comment]
I am going to amend my current github action setup script
```
node --version
npm install -g sfdx-cli
```

with the following version

```
node --version
npm install -g sfdx-cli
sfdx update --version 7.200.7
sfdx update stable-rc
sfdx version
sfdx update --version 7.198.6
```

**Comment by bdovh** [comment]
Still fails for me

**Comment by mshanemc** [comment]
@bdovh if you install via `npm` you're in this category and `sfdx update` doesn't do anything.

```
If you're in an environment where you manage your own node version, don't use node 18.16.0. We've had success on the previous, fairly recent versions 18.14.2 and 18.15.0
```

You can manage the node version used on GHA by passing a version to setup-node ([docs](https://github.com/actions/setup-node#supported-version-syntax)) like 

```yml
- uses: actions/setup-node@v3
  with:
    node-version: 18.15.0
```

**Comment by bdovh** [comment]
> @bdovh if you install via `npm` you're in this category and `sfdx update` doesn't do anything.
> 
> ```
> If you're in an environment where you manage your own node version, don't use node 18.16.0. We've had success on the previous, fairly recent versions 18.14.2 and 18.15.0
> ```
> 
> You can manage the node version used on GHA by passing a version to setup-node ([docs](https://github.com/actions/setup-node#supported-version-syntax)) like
> 
> ```yaml
> - uses: actions/setup-node@v3
>   with:
>     node-version: 18.15.0
> ```
does this mean I can't really test this fix?

**Comment by jdschleicher** [comment]
having issues (only in github actions and everything works locally) with package version creation not returning json or even creating package version to begin with. Found this issue through here through https://github.com/forcedotcom/cli/issues/2092

When i tried using "windows-latest" I didn't seem to have the issue but had incredibly long npm sfdx cli install times 

By following the updates here and the above article with "runs-on: ubuntu-latest" I've been having consistent success.

```

      - name: NODE INSTALL OVERWRITE FOR ISSUE https://github.com/forcedotcom/cli/issues/2125
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'

```

**Comment by jdayment** [comment]
I am on node v18.15 I tried both an updated version of SFDX CLI and uninstalled and installed the new SF CLI beta as well and am experiencing the same issues as being reported by others not sure what to try next

**Comment by cristiand391** [comment]
@jdayment can you provide more details?

`sfdx --version` and `sf --version` would help.

**Comment by jdayment** [comment]
Sure thing below is what I currently have installed I updated last night seeing if that might have been the issue I tried both on the latest SFDX version and the new beta 

@salesforce/cli/2.0.0-beta.50 win32-x64 node-v18.15.0

This is the command I am trying to run and it shows as done but no new package version is created 

PS C:\Users\jdayment\Desktop\Data Fetcher Bug Fixes\Data Fetcher Bux Fix\Data Fetcher Bug Fix> sf package create version --package "Data Fetcher" --code-coverage --installation-key-bypass --wait 10
Version create....
Version create.... done

**Comment by derrick-ejan-rs** [comment]
I was also getting issues with this node version. Had to specify to use 18.15.0.  Thanks for posting this.

**Comment by bdovh** [comment]
Should we keep using the workardound

      - name: NODE INSTALL OVERWRITE FOR ISSUE https://github.com/forcedotcom/cli/issues/2125
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'
          
or was the issue fixed?

**Comment by bdovh** [comment]
https://github.com/NomicFoundation/hardhat/issues/3877

**Comment by cristiand391** [comment]
@bdovh this was fixed in the CLI after changing the library it uses for zip files:

https://github.com/forcedotcom/cli/tree/main/releasenotes/sfdx#72046-june-8-2023
https://github.com/forcedotcom/source-deploy-retrieve/pull/975

bug report in upstream node:
https://github.com/nodejs/node/issues/48406

**Comment by coolbulevar** [comment]
Hello, we have started to face the issue with zip in static resource same time as this thread appeared, but it still happening even while using 
`@salesforce/cli/2.7.11 linux-x64 node-v18.17.0`

In static resource we have zip archive where one of the files have following path.
`force-app/main/default/staticresources/TemplateFrame/_rels/.rels`

And this files goes missing, affected operation `deploy start` and `package version create`.

The only workaround we have until now is to use `sfdx-cli@7.203.6 linux-x64 node-v16.20.0`

Any advise on that?

Thanks in advance.

**Comment by mshanemc** [comment]
@coolbulevar that sounds different.  

Can you open a new issue, hopefully sharing your staticResource that's causing the problem so we can replicate it?
