### ISSUE TITLE
Cannot read properties of null (reading 'replace')

### ISSUE THREAD

**Issue by viktor-saranchuk** [forcedotcom/cli#2149]
`sf deploy metadata -m ApexClass:<SomeClassName> ApexClass:<SomeClassNameTest> -l RunLocalTests -w 10 --verbose`

if I use RunSpecifiedTests it will pass

response Error (1): Cannot read properties of null (reading 'replace')

```
{
  "cliVersion": "@salesforce/cli/1.79.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.4.0",
  "shell": "zsh",
  "rootPath": "/Users/**/.local/share/sfdx/client/7.201.6-4edd82d/sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.2.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 3.0.1 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.14 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
    "@oclif/plugin-which 2.2.20 (core)",
    "@salesforce/cli 1.79.0 (core)",
    "apex 2.2.17 (core)",
    "auth 2.7.15 (core)",
    "data 2.3.16 (core)",
    "deploy-retrieve 1.8.5 (user)",
    "functions 1.21.9 (user)",
    "info 2.6.10 (core)",
    "limits 2.3.14 (core)",
    "login 1.2.8 (core)",
    "org 2.6.2 (user)",
    "schema 2.3.10 (core)",
    "settings 1.4.6 (core)",
    "sobject 0.1.18 (core)",
    "source 2.10.7 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.13 (core)",
    "trust 2.4.16 (core)",
    "user 2.3.10 (core)"
  ]
}
```

**Comment by iowillhoit** [comment]
Hello, I just tried to reproduce this and I was unable to. Could you please provide more details on how to reproduce this error? Preferably with a repo that I could clone. Thank you.

Steps I followed
- I installed `sf` version `1.79.0`
- Cloned [Dreamhouse](https://github.com/trailheadapps/dreamhouse-lwc) and followed the setup steps.
- Made some minor changes to the Apex class and associated test
- Ran `sf deploy metadata -m ApexClass:FileUtilities ApexClass:FileUtilitiesTest -l RunLocalTests -w 10 --verbose`
- This completed without error:
```
> sf deploy metadata -m ApexClass:FileUtilities ApexClass:FileUtilitiesTest -l RunLocalTests -w 10 --verbose
Warning: The "deploy metadata" command has been deprecated. Use "project deploy start" instead.
*** Deploying with SOAP API v57.0 ***
Deploy ID: 0Af520000242JXrCAM
Status: Succeeded | ████████████████████████████████████████ | 13/13 Components

Deployed Source
===================================================================================================
| State   Name              Type      Path
| ─────── ───────────────── ───────── ─────────────────────────────────────────────────────────────
| Changed FileUtilities     ApexClass force-app/main/default/classes/FileUtilities.cls
| Changed FileUtilities     ApexClass force-app/main/default/classes/FileUtilities.cls-meta.xml
| Changed FileUtilitiesTest ApexClass force-app/main/default/classes/FileUtilitiesTest.cls
| Changed FileUtilitiesTest ApexClass force-app/main/default/classes/FileUtilitiesTest.cls-meta.xml

Test Success [11]
✓ GeocodingServiceTest.blankAddress
✓ FileUtilitiesTest.createFileFailsWhenIncorrectBase64Data
✓ FileUtilitiesTest.createFileFailsWhenIncorrectFilename
✓ FileUtilitiesTest.createFileFailsWhenIncorrectRecordId
✓ FileUtilitiesTest.createFileSucceedsWhenCorrectInput
✓ GeocodingServiceTest.errorResponse
✓ TestSampleDataController.importSampleData
✓ GeocodingServiceTest.successResponse
✓ TestPropertyController.testGetPagedPropertyList
✓ TestPropertyController.testGetPicturesNoResults
✓ TestPropertyController.testGetPicturesWithResults

Apex Code Coverage
 Name                 % Covered Uncovered Lines
 ──────────────────── ───────── ───────────────
 FileUtilities        100%
 GeocodingService     100%
 PagedResult          100%
 PropertyController   95%       26,31
 SampleDataController 100%

Test Results Summary
Passing: 11
Failing: 0
Total: 11
Time: 3259
```

**Comment by iowillhoit** [comment]
Ah, I just realized you have a user installed version of `plugin-deploy-retrieve`. Try removing that with `sf plugins uninstall deploy-retrieve` and see if you are still having that issue. 

Unless you have a good reason to have core plugins over written, you should uninstall `(user)` plugins. I see `org` is also a user installed plugin.

**Comment by viktor-saranchuk** [comment]
<img width="822" alt="image" src="https://github.com/forcedotcom/cli/assets/40137179/c838974a-dc9e-4cf6-bfab-93968e68219f">

**Comment by viktor-saranchuk** [comment]
When I am using `sf project deploy start`
```
sf project deploy start -m ApexClass:ApexClass:SOM_Utils
Error (1): No source-backed components present in the package.
```
seems the documentation is not comprehensive

**Comment by viktor-saranchuk** [comment]
<img width="863" alt="image" src="https://github.com/forcedotcom/cli/assets/40137179/d547529b-d740-4156-8a59-eec4c64dde97">

**Comment by viktor-saranchuk** [comment]
<img width="602" alt="image" src="https://github.com/forcedotcom/cli/assets/40137179/de1911a8-f9fc-476a-a4ca-b16a4405219d">

**Comment by iowillhoit** [comment]
Still trying to replicate the `sf deploy metadata -m ApexClass:TheFile -l RunLocalTests` errors. 

It does look like your `sf project deploy start` is incorrect though. Try:
`sf project deploy start -m ApexClass:SOM_Utils`
instead of
`sf project deploy start -m ApexClass:ApexClass:SOM_Utils`

**Comment by viktor-saranchuk** [comment]
Thanks, I feel stupid right now )

**Comment by iowillhoit** [comment]
No worries! I'm on the CLI team and I still mess these commands up 😅

So I am not certain why this is happening and I still cannot reproduce it, but I was able to track down where the error is coming from. Could you share the json results of your command by using the `--json` flag? I am interested in the structure of the test `failures`

**Comment by PalGenadich** [comment]
@iowillhoit This happens when there are Test Failures to display. It throws an exception when trying to display test failures.
I see a failure structure like this in response:
```
          {
            "id": "01p1U00000Qtc6EQAR",
            "message": "line 11, column 36: Dependent class is invalid and needs recompilation:\n Class blaBlaClass bla bla actual compilation error",
            "methodName": "",
            "name": "someTestName",
            "namespace": null,
            "packageName": "someTestName",
            "stackTrace": null,
            "time": -1,
            "type": "Class"
          }
```
The bug is right here: https://github.com/salesforcecli/plugin-deploy-retrieve/blob/main/src/formatters/deployResultFormatter.ts#LL317
The code doesn't handle `stackTrace==null`.
Please fix. :)

**Comment by iowillhoit** [comment]
Hey @PalGenadich! Yep, that is what I had tracked down too! Thank you for providing the output of a test that causes this to fail. I just wanted to confirm that a test was indeed coming back with an empty `stackTrace` or if something else was going on. I will log a ticket and we'll get this sorted out. Thanks again 👍

**Comment by iowillhoit** [comment]
A fix has been merged in! It will be available in tomorrow's `nightly` build.

**Comment by Llnski** [comment]
I am still having this issue:
```
 {
            "id": "01D151EA84AC889AAD",
            "message": "line 18, column 44: Invalid type: InteractionSummary",
            "methodName": "",
            "name": "GetRecordId",
            "namespace": null,
            "packageName": "GetRecordId",
            "stackTrace": null,
            "time": -1,
            "type": "Class"
          }
```

**Comment by cristiand391** [comment]
this was fixed in sf v1.81.0.
https://github.com/forcedotcom/cli/tree/main/releasenotes/sf#1810-june-7-2023-stable

**Comment by Llnski** [comment]
Please reopen this @cristiand391, I'm using sf v1.81.6 and am still having the issue.

**Comment by cristiand391** [comment]
@Llnski do you have a way to repro the issue on latest? I'm having a hardtime trying to trigger the failure again.

Also, can you share the output of `sf version --verbose`?

**Comment by Llnski** [comment]
@cristiand391  here is the output of  ``sf version --verbose`` from Powershell:
```
CLI Version:
        @salesforce/cli/1.82.0

 Architecture:
        win32-x64

 Node Version:
        node-v18.15.0

 Plugin Version:
        @oclif/plugin-autocomplete 2.3.0 (core)
        @oclif/plugin-commands 2.2.15 (core)
        @oclif/plugin-help 5.2.9 (core)
        @oclif/plugin-not-found 2.3.24 (core)
        @oclif/plugin-plugins 3.1.2 (core)
        @oclif/plugin-search 0.0.17 (core)
        @oclif/plugin-update 3.1.16 (core)
        @oclif/plugin-version 1.3.4 (core)
        @oclif/plugin-warn-if-update-available 2.0.37 (core)
        @oclif/plugin-which 2.2.21 (core)
        @salesforce/cli 1.82.0 (core)
        apex 2.2.22 (core)
        auth 2.7.17 (core)
        data 2.3.20 (core)
        deploy-retrieve 1.11.0 (core)
        info 2.6.16 (core)
        limits 2.3.17 (core)
        login 1.2.11 (core)
        org 2.9.3 (core)
        schema 2.3.10 (core)
        settings 1.4.10 (core)
        sobject 0.1.22 (core)
        source 2.10.12 (core)
        telemetry 2.2.0 (core)
        templates 55.4.18 (core)
        trust 2.4.20 (core)
        user 2.3.14 (core)

 OS and Version:
        Windows_NT 10.0.19045

 Shell:
        cmd.exe

 Root Path:
        C:\Users\User\AppData\Local\sfdx\client\7.204.6-fbe290c\sf
```
[Additionally, here is the Repro.](https://github.com/Llnski/SF-repro.git)

**Comment by cristiand391** [comment]
@Llnski thanks!

I cloned the repo, created the scratch org and the deploy worked fine:
```
➜  SF-repro git:(main) sf project deploy start -o apex-bug
Deploying v57.0 metadata to test-ermskruqdk1t@example.com using the v58.0 SOAP API.
Deploy ID: 0AfDS000033GTs60AG
Status: Succeeded | ████████████████████████████████████████ | 1/1 Components
                                                                                                                                                                          
Deployed Source
===================================================================================
| State   Name      Type      Path
| ─────── ───────── ───────── ─────────────────────────────────────────────────────
| Created EmailSend ApexClass force-app/main/default/classes/EmailSend.cls
| Created EmailSend ApexClass force-app/main/default/classes/EmailSend.cls-meta.xml
```

then created an apex class and tried deploying and running tests in org:
```
➜  SF-repro git:(main) ✗ sf project deploy start -o apex-bug --test-level RunLocalTests -w 10 --verbose --metadata ApexClass:Lala
Deploying v57.0 metadata to test-uix0ei4qsxa1@example.com using the v58.0 SOAP API.
Deploy ID: 0AfDa00001Q9eAMKAZ
Status: Failed | ████████████████████████████████████████ | 1/1 Components
                                                                                                                                                                          
Apex Code Coverage
 Name      % Covered Uncovered Lines
 ───────── ───────── ───────────────
 EmailSend 0%        2,4
 Lala      0%        2
                                                                                                                                                                          
Test Results Summary
Passing: 0
Failing: 0
Total: 0
```

also looked at the json output and couldn't find any ref to `stackTrace` == `null`, is there any step I'm missing?

**Comment by Llnski** [comment]
Thank you for verifying @cristiand391, and that's odd, I just reinstalled the salesforce cli and updated my node installation -- no dice. I'm wondering if it has something to do with the way my org is configured? The issue is a type error on ``InteractionSummary``, which is [apparently a data model](https://help.salesforce.com/s/articleView?id=release-notes.rn_fsc_interaction_summary_container.htm&release=230&type=5). Do you know of any way to get a better stacktrace on the two errors? 
```
 GetRecordId.
  message: line 18, column 44: Invalid type: InteractionSummary

• getRecordIdForAura.
  message: line 13, column 44: Invalid type: InteractionSummary
```

**Comment by cristiand391** [comment]
@Llnski is there any more details in the deployment status?

run `sf org open -p lightning/setup/DeployStatus/home` and go to the failed deployment.

**Comment by Llnski** [comment]
![image](https://github.com/forcedotcom/cli/assets/58711251/dc72425c-4726-42f4-9b76-cb5e319e68b2)
@cristiand391 nope, it's the same thing.

**Comment by Llnski** [comment]
![image](https://github.com/forcedotcom/cli/assets/58711251/fdcf9400-1968-4b57-8357-24d4f0ea1abd)
Found the issue. This must be some default finserv thing.
