### ISSUE TITLE
Unvalidated package `The release specified for the package version was invalid. Release : .`

### ISSUE THREAD

**Issue by Kevmo92** [forcedotcom/cli#2251]
### Summary
Trying to create an unvalidated package and I'm getting an error that doesn't make sense.

### Steps To Reproduce

- authenticate to our dev hub
- run sfdx cli command:
`sfdx package version create --version-name 1.493.0.0 --branch release --version-number 1.493.0.0 --package "nCino Bank Operating System" --installation-key $PACKAGE_KEY --version-description "test" --tag PACKAGE_KEY=$PACKAGE_KEY --skip-validation --json`
- receive error

### Expected result
I'm expecting a package version to be created.

### Actual result
{
  "code": 1,
  "context": "PackageVersionCreateCommand",
  "commandName": "PackageVersionCreateCommand",
  "message": "The release specified for the package version was invalid. Release : .",
  "name": "INVALID_INPUT",
  "status": 1,
  "stack": "INVALID_INPUT: The release specified for the package version was invalid. Release : .\n    at HttpApi.getError (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/jsforce/lib/http-api.js:252:12)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/jsforce/lib/http-api.js:122:23\n    at async Tooling.create (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/jsforce/lib/connection.js:794:133)\n    at async PackageVersionCreate.packageVersionCreate (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/packaging/lib/package/packageVersionCreate.js:486:30)\n    at async Function.create (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/packaging/lib/package/packageVersion.js:92:30)\n    at async PackageVersionCreateCommand.run (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-packaging/lib/commands/package/version/create.js:60:24)\n    at async PackageVersionCreateCommand._run (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/command.js:117:22)\n    at async Config.runCommand (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:329:25)\n    at async run (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/main.js:89:16)",
  "exitCode": 1,
  "warnings": []
}

### System Information
zsh 
```json
{
  "cliVersion": "sfdx-cli/7.204.6",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.20.0",
  "osVersion": "Darwin 22.3.0",
  "shell": "zsh",
  "rootPath": "/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.24 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.16 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.37 (core)",
    "@oclif/plugin-which 2.2.21 (core)",
    "apex 2.2.22 (core)",
    "auth 2.7.17 (core)",
    "community 2.3.0 (core)",
    "custom-metadata 2.1.24 (core)",
    "data 2.3.20 (core)",
    "deploy-retrieve 1.11.0 (core)",
    "info 2.6.16 (core)",
    "limits 2.3.17 (core)",
    "org 2.9.3 (core)",
    "packaging 1.18.0 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.10 (core)",
    "signups 1.4.20 (core)",
    "source 2.10.12 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.18 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.14 (core)",
    "isvte-sfdx-plugin 1.1.15 (user)",
    "sfdx-cli 7.204.6 (core)"
  ]
}
```
### Additional information
Our sfdx-project.json looks like:
```
{
    "namespace": "nCino",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "57.0",
    "packageDirectories": [
        {
            "path": "node_modules/@ncino/force-sdk-nwc/modules"
        },
        {
            "path": "src/nCino",
            "package": "nCino Bank Operating System",
            "ancestorVersion": "HIGHEST",
            "versionName": "ver 0.0.0.0",
            "versionNumber": "0.NEXT.0.0",
            "definitionFile": "config/project-scratch-def.json",
            "dependencies": [
                {
                    "package": "nFORCE_2.1570"
                },
                {
                    "package": "nDESIGN_2.43"
                },
                {
                    "package": "LLC_BI_2.1912"
                },
                {
                    "package": "nFUSE_2.463"
                }
            ],
            "default": true,
            "unpackagedMetadata": {
                "path": "src/unpackaged/indirect-lending/profiles"
            }
        },
        {
            "path": "src/unpackaged/indirect-lending/profiles",
            "default": false
        }
    ],
    "packageAliases": {
        "nCino Bank Operating System": "0Ho3n000000KyjuCAC",
        "nFORCE_2.1570": "04t6S000000tMg3QAE",
        "nDESIGN_2.43": "04t0W0000015eWUQAY",
        "LLC_BI_2.1912": "04t4U0000011W8uQAE",
        "nFUSE_2.463": "04t1R0000016ZygQAE"
    }
}
```

**Comment by Kevmo92** [comment]
with
```
{
  "cliVersion": "sfdx-cli/7.206.6",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.20.0",
  "osVersion": "Darwin 22.3.0",
  "shell": "zsh",
  "rootPath": "/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.25 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.18 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.37 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "apex 2.3.3 (core)",
    "auth 2.8.1 (core)",
    "community 2.3.2 (core)",
    "custom-metadata 2.1.26 (core)",
    "data 2.3.24 (core)",
    "deploy-retrieve 1.12.0 (core)",
    "info 2.6.20 (core)",
    "limits 2.3.20 (core)",
    "org 2.9.12 (core)",
    "packaging 1.20.0 (core)",
    "schema 2.3.13 (core)",
    "settings 1.4.12 (core)",
    "signups 1.4.22 (core)",
    "source 2.10.15 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.4.21 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.17 (core)",
    "isvte-sfdx-plugin 1.1.15 (user)",
    "sfdx-cli 7.206.6 (core)"
  ]
}
```

in place, I still receive an error:

```
{
  "code": 1,
  "context": "PackageVersionCreateCommand",
  "commandName": "PackageVersionCreateCommand",
  "message": "Cannot convert undefined or null to object",
  "name": "TypeError",
  "status": 1,
  "stack": "TypeError: Cannot convert undefined or null to object\n    at Function.entries (<anonymous>)\n    at fileContentsRawToAliasStore (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/stateAggregator/accessors/aliasAccessor.js:245:27)\n    at AliasAccessor.readFileToAliasStore (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/stateAggregator/accessors/aliasAccessor.js:187:31)\n    at async AliasAccessor.init (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/stateAggregator/accessors/aliasAccessor.js:176:9)\n    at async Function.create (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/creatable.js:57:9)\n    at async StateAggregator.init (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/stateAggregator/stateAggregator.js:40:24)\n    at async Function.create (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/creatable.js:57:9)\n    at async Function.getInstance (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/stateAggregator/stateAggregator.js:24:66)\n    at async Org.init (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/org.js:747:33)\n    at async Function.create (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/creatable.js:57:9)\n    at async getHubOrThrow (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/sf-plugins-core/lib/flags/orgFlags.js:75:17)\n    at async Parser._flags (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/parser/parse.js:234:76)\n    at async Parser.parse (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/parser/parse.js:161:23)\n    at async Object.parse (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/parser/index.js:18:20)\n    at async PackageVersionCreateCommand.parse (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/command.js:221:25)\n    at async PackageVersionCreateCommand.run (/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-packaging/lib/commands/package/version/create.js:21:27)",
  "exitCode": 1,
  "warnings": []
}
```
Good try though bot.

**Comment by WillieRuemmele** [comment]
Hey @Kevmo92 has this command worked for you in the past?

**Comment by Kevmo92** [comment]
@WillieRuemmele Hey! Yes this command has previously worked. It seems like I'm getting caught in some ancestor check, but the error I'm getting, `The release specified for the package version was invalid. Release : .`, doesn't make sense to me 🤔 I'm not specifying a release.

**Comment by WillieRuemmele** [comment]
@Kevmo92 interesting, do you know, or could you find out what version it was working on? There is the `--skip-ancestor-check` flag, you might try adding that for now if that's what's happening

**Comment by burntsugar** [comment]
I am also getting unexpected errors on `sfdx package version create` - it seems the options are not parsing even tho they are correct. This has only happened overnight, on Azure with Docker image **salesforce/salesforcedx:latest-full** df8c718633e05aa60ca612838da530e74022f948ca50c13e7ea10d8e9488c579 (sf cli (7.207.3). The command works fine on my local machine (sf cli 7.201.6).

`sf package version create --skip-validation --package PKGNAME --installation-key KEY --definition-file config/project-scratch-def.json --target-dev-hub ALIAS --json`

`{
  "code": 1,
  "context": "PackageVersionCreateCommand",
  "commandName": "PackageVersionCreateCommand",
  "message": "Flag --installation-key expects a value",
  "name": "Error",
  "status": 1,
  "stack": "Error: Flag --installation-key expects a value\n    at parseFlag (/home/vsts_azpcontainer/.local/share/sf/node_modules/@oclif/core/lib/parser/parse.js:112:27)\n    at Parser.parse (/home/vsts_azpcontainer/.local/share/sf/node_modules/@oclif/core/lib/parser/parse.js:137:21)\n    at Object.parse (/home/vsts_azpcontainer/.local/share/sf/node_modules/@oclif/core/lib/parser/index.js:18:33)\n    at PackageVersionCreateCommand.parse (/home/vsts_azpcontainer/.local/share/sf/node_modules/@oclif/core/lib/command.js:221:38)\n    at PackageVersionCreateCommand.run (/home/vsts_azpcontainer/.local/share/sf/node_modules/@salesforce/plugin-packaging/lib/commands/package/version/create.js:21:38)\n    at PackageVersionCreateCommand._run (/home/vsts_azpcontainer/.local/share/sf/node_modules/@oclif/core/lib/command.js:117:33)",
  "exitCode": 1,
  "warnings": []
}
`

**Comment by WillieRuemmele** [comment]
HI @burntsugar - I think that issue is related to something else that we're reverting as I'm typing... I still think there's something wrong with the PVC command

**Comment by WillieRuemmele** [comment]
Hi @Kevmo92 - after digging into the error more, could you revert your CLI version to `7.204.6` and then try modifying some files locally to help us confirm?

could you modify `/Users/kevinwatson/.fnm/node-versions/v16.20.0/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/packaging/lib/package/packageVersionCreate.js:486:30` to remove the `options` parameter passed as the last argument?

it was added recently and _might_ be the cause

https://github.com/forcedotcom/packaging/pull/302/files#diff-ba9d3115c9ec130439cf42057c652e2fa8b07105e4a6350b05531a5263fa27edL662

**Comment by Kevmo92** [comment]
@WillieRuemmele Thanks for the suggestion. Using CLI `7.204.6` and removing options from the line you mentioned 
![Screenshot 2023-06-27 at 4 03 17 PM](https://github.com/forcedotcom/cli/assets/9120034/0f79f201-840b-44aa-811f-90475a37cfb9)

still gave the same error of 
```{
  "code": 1,
  "context": "PackageVersionCreateCommand",
  "commandName": "PackageVersionCreateCommand",
  "message": "The release specified for the package version was invalid. Release : .",
  "name": "INVALID_INPUT",
  "status": 1,
  "stack": "INVALID_INPUT: The release specified for the package version was invalid. Release : .\n    at HttpApi.getError (/Users/kevinwatson/.fnm/node-versions/v16.20.1/installation/lib/node_modules/sfdx-cli/node_modules/jsforce/lib/http-api.js:252:12)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /Users/kevinwatson/.fnm/node-versions/v16.20.1/installation/lib/node_modules/sfdx-cli/node_modules/jsforce/lib/http-api.js:122:23\n    at async Tooling.create (/Users/kevinwatson/.fnm/node-versions/v16.20.1/installation/lib/node_modules/sfdx-cli/node_modules/jsforce/lib/connection.js:794:133)\n    at async PackageVersionCreate.packageVersionCreate (/Users/kevinwatson/.fnm/node-versions/v16.20.1/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/packaging/lib/package/packageVersionCreate.js:486:30)\n    at async Function.create (/Users/kevinwatson/.fnm/node-versions/v16.20.1/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/packaging/lib/package/packageVersion.js:92:30)\n    at async PackageVersionCreateCommand.run (/Users/kevinwatson/.fnm/node-versions/v16.20.1/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-packaging/lib/commands/package/version/create.js:60:24)\n    at async PackageVersionCreateCommand._run (/Users/kevinwatson/.fnm/node-versions/v16.20.1/installation/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/command.js:117:22)\n    at async Config.runCommand (/Users/kevinwatson/.fnm/node-versions/v16.20.1/installation/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:329:25)\n    at async run (/Users/kevinwatson/.fnm/node-versions/v16.20.1/installation/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/main.js:89:16)",
  "exitCode": 1,
  "warnings": []
}
```

Let me know if you want me to try something else!

**Comment by burntsugar** [comment]
> HI @burntsugar - I think that issue is related to something else that we're reverting as I'm typing... I still think there's something wrong with the PVC command

Is there an update on this?

**Comment by WillieRuemmele** [comment]
yes, that flag issue should be resolved in the latest version of `@oclif/core : 2.8.10`

**Comment by Kevmo92** [comment]
@WillieRuemmele wanted to let you know I tried adding the `--skip-ancestor-check` flag to the package version create command I'm still getting `Error (1): The release specified for the package version was invalid. Release : .`

Let me know if you need me to try something else. I'm also seeing a similar error in a barebones project that just has dummy code.

**Comment by shetzel** [comment]
@Kevmo92 - can we access that barebones project you mentioned to try to reproduce this?  Without that, we'll have to punt this to the packaging team.  It would also help narrow this down to find the last working CLI version for your usecase.

**Comment by shetzel** [comment]
From the packaging team: "This error: `The release specified for the package version was invalid.` is thrown when the scratch org definition file passed to the version create command specifies the [“release” attribute](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_def_file.htm) with invalid value."

**Comment by Kevmo92** [comment]
@shetzel You're saying that specifying a "release" tag in the project-scratch-def.json affects the way the package create command works? Can you explain that a little more? It's confusing since the release tag documentation on the link you sent only says this

```
Same Salesforce release as the Dev Hub org. Options are preview or previous. Can use only during Salesforce release transition periods.
```

**Comment by Kevmo92** [comment]
@shetzel I finally saw where it was getting a "release" tag from. The project-scratch-def.json had an empty `release` key put in during the build process 🤦 

I'm able to create unvalidated and validated packages again when I don't have an empty `release` specified.
