### ISSUE TITLE
Can't open scratch orgs that were created last week

### ISSUE THREAD

**Issue by homerlex** [forcedotcom/cli#262]
### Summary

Can't open scratch orgs that were created last week.  I have a number of scartch orgs that were created last week.  I was using them fine on Friday (1/3/2020).  This morning (1/6/2020) when I try "sfdx force:org:open" on any of these orgs the command line hangs indefinitely.  If I create a new scratch org I can open it with any problem.

### Steps To Reproduce:

1.  sfdx force:org:open - <some org that was created 1/3/2020 or prior>

### Expected result

Org should open in the browser

### Actual result

The command line hangs indefinitely. 

### Additional information

I also tried the -r option to try just getting the url and that hangs too 

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.37.1 win32-x64 node-v10.15.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.2.2 (core)
generator 1.1.2 (core)
salesforcedx 47.10.1
├─ salesforcedx-templates 47.11.0
└─ salesforce-alm 47.11.0

**OS and version**:
Window 10

**Comment by keirbowden** [comment]
We saw the same thing earlier today - strangely there was one member of the team who was unaffected. They were signed out of the dev hub and when they signed back in again they could access their existing scratch orgs. The rest of us (5 people) lost access to all of them.

**Comment by ImJohnMDaniel** [comment]
I have also seen similar behavior over the weekend

**Comment by ajw725** [comment]
same issue here for all of my existing scratch orgs. sometimes i get this error:

```
::% sfdx force:org:display
(node:6609) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added. Use emitter.setMaxListeners() to increase limit
```

also, if i do `ps | grep force` while that command is running, it looks like there are several processes running:
```
::% ps | grep force
 7114 ttys004    0:00.01 sfdx force:org:display
 7115 ttys004    0:00.00 bash /Users/andrewweinstein/.local/share/sfdx/client/bin/sfdx force:org:display
 7120 ttys004    0:00.00 bash /Users/andrewweinstein/.local/share/sfdx/client/bin/../7.36.0-b1c4e9c7c8/bin/sfdx force:org:display
 7126 ttys004    0:00.77 /Users/andrewweinstein/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node /Users/andrewweinstein/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/sfdx.js force:org:display
 7160 ttys005    0:00.00 grep force
```
i'm not sure if that's expected, but it seems like there should only be one.

**Comment by aheber** [comment]
I had the same issue.

I don't know what pod I was on but do you think it is possible that scratch orgs on the now Spring '20 pods didn't survive the upgrade?

**Comment by shetzel** [comment]
Thanks for reporting everyone.  There hasn't been any CLI changes for several weeks but as was pointed out in this thread there was an update over the weekend, which seems to be causing the problem.

This will be better handled as a support case.  Could one of you please contact support to start that process?  I will close this issue as being tracked internally.

Thanks all!

**Comment by daveespo** [comment]
Case #25282353

**Comment by daveespo** [comment]
FWIW, this seems to have been fixed for us. We can open scratch orgs that were created last week

**Comment by ajw725** [comment]
yep, working for me now, too. still can't create a new scratch org on the preview release, but there's another issue here for that.
