### ISSUE TITLE
force:data:soql:query prints [object Object] for related related record

### ISSUE THREAD

**Issue by YodaDaCoda** [forcedotcom/cli#264]
### Summary

When querying data with `sfdx force:data:soql:query`, related fields more than two levels deep just display as `[object Object]`.

### Steps To Reproduce:

1.  `sfdx force:data:soql:query -q "SELECT Id, Sobj1__r.Sobj2__r.Some_Field__c`
1.  Note that the output fields are `Id` and `Sobj1__r.Sobj2__r`. The value for `Sobj1__r.Sobj2__r` is `[object Object]` which is the standard javascript string representation of an object.

### Expected result

I should get the value of `Id` and `Some_Field__c` in my output.

### Actual result

I get the `Id` and `[object Object]` in my output.

### Additional information

I wrote a patch for the to process columns recursively, which is working beautifully for me, but I don't know if it'll be of any use to you internally. See attached: [dataSoqlQueryCommand.patch.txt](https://github.com/forcedotcom/cli/files/4038761/dataSoqlQueryCommand.patch.txt)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.36.0-b1c4e9c7c8 linux-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.9.0 (core)
├─ salesforcedx-templates 47.9.0 (core)
└─ salesforce-alm 47.10.0 (core)

sfdx-cli 7.36.0 (core)

**OS and version**:
Ubuntu 19.10 (eoan)

**Comment by clairebianchi** [comment]
@YodaDaCoda We are going to look into this issue. Thank you

**Comment by tescalada** [comment]
Thanks so much for this patch @YodaDaCoda. I've been applying this patch to workaround this issue successfully for the past year until today. It seems to have broken at version sfdx-cli/7.84.2-a2868a68d5 linux-x64 node-v12.18.3
 which has changed enough to break it. Attached is a new diff that seems to work for me (hopefully its not breaking something else that I have just not yet run into).

[dataSoqlQueryCommand.7.84.2.patch.txt](https://github.com/forcedotcom/cli/files/5952520/dataSoqlQueryCommand.7.84.2.patch.txt)

**Comment by WillieRuemmele** [comment]
Hi @YodaDaCoda @tescalada  check out the [announcement](https://github.com/forcedotcom/cli/issues/907) for the new [data](https://github.com/forcedotcom/cli/issues/907) plugin

**Comment by mshanemc** [comment]
I think this is fixed in the new data plugin released 4/1.  If not, re-open or create a new case.

**Comment by eburtness** [comment]
@mshanemc I'm still getting [object Object] -- is 0.4.3 the new plugin?

```
PS C:\Users\eburtness\source\repos\salesforce> sfdx update        
sfdx-cli: Updating CLI... already on latest version: 7.94.3-a4e7c7955b
sfdx-cli: Updating plugins... done
PS C:\Users\eburtness\source\repos\salesforce> sfdx plugins --core
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.5.1 (core)
config 1.2.7 (core)
generator 1.1.5 (core)
salesforcedx 51.6.0 (core)
├─ data 0.4.3 (core)
├─ limits 1.0.4 (core)
├─ schema 1.0.4 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ org 1.6.0 (core)
├─ user 1.2.1 (core)
├─ templates 51.3.0 (core)
└─ salesforce-alm 51.6.6 (core)
sfdx-cli 7.94.3 (core)
telemetry 1.1.1 (core)
PS C:\Users\eburtness\source\repos\salesforce> sfdx force:data:soql:query -q "SELECT AccountId, Account.FinServ__PrimaryContact__c, Account.FinServ__PrimaryContact__r.AccountId FROM AccountContactRelation LIMIT 5" 
ACCOUNTID           ACCOUNT.FINSERV__PRIMARYCONTACT__C  ACCOUNT.FINSERV__PRIMARYCONTACT__R
──────────────────  ──────────────────────────────────  ──────────────────────────────────
0012S000026my6GQAQ  0032S000026t7NxQAI                  [object Object]
0012S000026my6fQAA  0032S000026t7NxQAI                  [object Object]
0012S000026my6fQAA  0032S000026t7NxQAI                  [object Object]
0012S000026my6fQAA  0032S000026t7NxQAI                  [object Object]
0012S000026my6fQAA  0032S000026t7NxQAI                  [object Object]
Total number of records retrieved: 5.
Querying Data... done
```

**Comment by tescalada** [comment]
@YodaDaCoda I ported your patch over to the new data plugin so I could continue making some deep queries. Feel free to fork and submit the patch upstream as it was your code to begin with. If that's more trouble than its worth and you want me to submit the patch let me know, I am happy to do that too with your approval.

**Comment by MuriloKakazu** [comment]
@mshanemc This is not fixed in `@salesforce/plugin-data@0.6.0`, which is currently the latest version of the plugin :(

![image](https://user-images.githubusercontent.com/15305591/128883803-ec767ed8-b7ce-42fa-a09f-a8e28823b77a.png)

**Comment by MuriloKakazu** [comment]
@clairebianchi @WillieRuemmele 👆

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9733069](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000Tf3bYAC/view)
