### ISSUE TITLE
[Error] FieldService : externalized text label not found, section: 'SchedulingWorkspaceFilter' missing 

### ISSUE THREAD

**Issue by mamikals** [forcedotcom/cli#2702]
### Summary

I am encountering an error when trying to create a scratch org with Field Service enabled in the new Spring 24 release.
`[Error] FieldService : externalized text label not found, section: 'SchedulingWorkspaceFilter' missing `
I have the following features and settings enabled, and everything works when I remove the settings for fieldService (except that fieldService is disabled).
```
{
    "edition": "Enterprise",
    "release": "Current",
    "features": [
        "FieldService:5",
        "FieldServiceDispatcherUser:5",
        "FieldServiceMobileUser:5",
        "FieldServiceSchedulingUser:5"
    ],
    "country": "NO",
    "language": "en_US",
    "settings": {
        "fieldServiceSettings": {
            "fieldServiceOrgPref": true,
            "doesShareSaParentWoWithAr": false,
            "doesShareSaWithAr": false,
            "enableWorkOrders": true,
            "isGeoCodeSyncEnabled": false,
            "isLocationHistoryEnabled": false,
            "fieldServiceNotificationsOrgPref": false,
            "serviceAppointmentsDueDateOffsetOrgValue": 7,
            "workOrderLineItemSearchFields": "Subject",
            "workOrderSearchFields": "Subject"
        }
    }
}
```

### Steps To Reproduce
Create a scratch with fieldService enabled 

### Expected result
The scratch should be created without issue and fieldService should be enabled.

### Actual result
The scratch fails to create because of an error in the fieldService settings.

### System Information
Running on cmd, using windows 10 for local runs. Github CLI is running bash with newest version of the CLI.
My version is the following.

```json
{
  "cliVersion": "@salesforce/cli/2.9.8",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.19.0",
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\M162489\\AppData\\Roaming\\nvm\\v18.19.0\\node_modules\\@salesforce\\cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.8 (core)",
    "@oclif/plugin-commands 2.2.25 (core)",
    "@oclif/plugin-help 5.2.19 (core)",
    "@oclif/plugin-not-found 2.4.1 (core)",
    "@oclif/plugin-plugins 3.6.1 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.3 (core)",
    "@oclif/plugin-version 1.3.10 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.0 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.9.8 (core)",
    "apex 2.3.14 (core)",
    "auth 2.8.16 (core)",
    "data 2.5.9 (core)",
    "deploy-retrieve 1.17.13 (core)",
    "info 2.6.42 (core)",
    "limits 2.3.34 (core)",
    "login 1.2.30 (core)",
    "marketplace 0.2.1 (core)",
    "org 2.10.7 (core)",
    "packaging 2.1.0 (user)",
    "schema 2.3.25 (core)",
    "settings 1.4.28 (core)",
    "sobject 0.2.7 (core)",
    "source 2.10.33 (core)",
    "telemetry 2.3.2 (core)",
    "templates 55.5.11 (core)",
    "trust 2.6.10 (core)",
    "user 2.3.32 (core)",
    "sfpowerkit 6.1.0 (user)"
  ]
}
```

**Comment by mamikals** [comment]
I updated my CLI just to try and i'm still experiencing the error. My current version is the following.
```json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.27.6",
  "nodeVersion": "node-v18.19.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\M162489\\AppData\\Roaming\\nvm\\v18.19.0\\node_modules\\@salesforce\\cli",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.5 (core)",
    "@oclif/plugin-commands 3.1.1 (core)",
    "@oclif/plugin-help 6.0.12 (core)",
    "@oclif/plugin-not-found 3.0.9 (core)",
    "@oclif/plugin-plugins 4.1.23 (core)",
    "@oclif/plugin-search 1.0.12 (core)",
    "@oclif/plugin-update 4.1.8 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.9 (core)",
    "@oclif/plugin-which 3.0.15 (core)",
    "@salesforce/cli 2.27.6 (core)",
    "apex 3.0.22 (core)",
    "auth 3.3.6 (core)",
    "data 3.0.18 (core)",
    "deploy-retrieve 3.2.9 (core)",
    "info 3.0.19 (core)",
    "limits 3.1.6 (core)",
    "marketplace 1.0.20 (core)",
    "org 3.3.10 (core)",
    "packaging 2.1.0 (user)",
    "schema 3.1.0 (core)",
    "settings 2.0.21 (core)",
    "sobject 1.1.6 (core)",
    "source 3.1.8 (core)",
    "telemetry 3.1.10 (core)",
    "templates 56.0.12 (core)",
    "trust 3.3.4 (core)",
    "user 3.2.6 (core)",
    "sfpowerkit 6.1.0 (user)"
  ]
}
```

**Comment by GodertC** [comment]
I'm also experiencing this issue/

`@salesforce/cli/2.27.6 linux-x64 node-v18.19.0
@oclif/plugin-autocomplete 3.0.5 (core)
@oclif/plugin-commands 3.1.1 (core)

@oclif/plugin-not-found 3.0.9 (core)
@oclif/plugin-plugins 4.1.23 (core)
@oclif/plugin-search 1.0.12 (core)
@oclif/plugin-update 4.1.8 (core)
@oclif/plugin-version 2.0.11 (core)
@oclif/plugin-warn-if-update-available 3.0.9 (core)

@salesforce/cli 2.27.6 (core)`

**Comment by chfosli** [comment]
Just got confirmation from Salesforce support that this is a bug.

> Our engineering team has confirmed that the issue is coming due to the latest Spring'24 release. They have created a work item# W-15018785 to fix the issue and the fix patch is going to be made today itself by EOD GMT hours. Moreover we have created a public facing known issue for our customers so that they can "Report" (use the button on the KI) that they are affected by the known issue and any change in the progress/status of the issue would trigger an email update to the Reported users.

https://issues.salesforce.com/issue/a028c00000yx0wjAAA/

**Comment by mamikals** [comment]
Issue seems to have been fixed.

**Comment by GodertC** [comment]
This issue has not been fixed I'm still experiencing this error.

**Comment by chfosli** [comment]
> This issue has not been fixed I'm still experiencing this error.

They are rolling the fix out, so maybe your instances have not got the fix yet: https://status.salesforce.com/generalmessages/1315
