### ISSUE TITLE
Run test for a suite Name Error

### ISSUE THREAD

**Issue by oussamaElwess** [forcedotcom/cli#3408]
Hello ,

I have an issue when i run a run test for a suite Name : 

**Command** : sf apex run test --test-level RunSpecifiedTests --suite-names MySuite

**Error (INVALID_INPUT**): Si le testLevel est RunSpecifiedTests, vous ne pouvez pas spécifier des catégories de test.

Thank you for your help

**Comment by oussamaElwess** [comment]
My Cli Version is : 
 sf version --verbose --json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.107.6",
  "nodeVersion": "node-v22.19.0",
  "osVersion": "Windows_NT 10.0.26100",
  "rootPath": "C:\\Users\\ol\\AppData\\Local\\sf\\client\\2.107.6-2909b3c",
  "shell": "powershell",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.34 (core)",
    "@oclif/plugin-commands 4.1.33 (core)",
    "@oclif/plugin-help 6.2.33 (core)",
    "@oclif/plugin-not-found 3.2.68 (core)",
    "@oclif/plugin-plugins 5.4.47 (core)",
    "@oclif/plugin-search 1.2.30 (core)",
    "@oclif/plugin-update 4.7.5 (core)",
    "@oclif/plugin-version 2.2.33 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.48 (core)",
    "@oclif/plugin-which 3.2.40 (core)",
    "@salesforce/cli 2.107.6 (core)",
    "agent 1.24.10 (core)",
    "apex 3.8.0 (core)",
    "api 1.3.3 (core)",
    "auth 3.9.7 (core)",
    "data 4.0.56 (core)",
    "deploy-retrieve 3.23.3 (core)",
    "info 3.4.87 (core)",
    "limits 3.3.67 (core)",
    "marketplace 1.3.8 (core)",
    "org 5.9.28 (core)",
    "packaging 2.20.3 (core)",
    "schema 3.3.81 (core)",
    "settings 2.4.48 (core)",
    "sobject 1.4.73 (core)",
    "telemetry 3.6.56 (core)",
    "templates 56.3.65 (core)",
    "trust 3.7.113 (core)",
    "user 3.6.38 (core)"
  ]
}

**Comment by jprichter** [comment]
I'm getting the same thing with a recent update to 108.6. Was not getting this error on 106.6

`sf apex run test --suite-names mySuite -o myOrg`

Error (INVALID_INPUT): If the testLevel is RunSpecifiedTests, you may not specify test categories.
 sf version --verbose --json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.108.6",
  "nodeVersion": "node-v22.15.0",
  "osVersion": "Windows_NT 10.0.22631",
  "rootPath": "C:\\UserDir\\AppData\\Local\\Programs\\node-v22.15.0-win-x64\\node_modules\\@salesforce\\cli",
  "shell": "C:\\UserDir\\AppData\\Local\\Programs\\Git\\usr\\bin\\bash.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.35 (core)",
    "@oclif/plugin-commands 4.1.33 (core)",
    "@oclif/plugin-help 6.2.33 (core)",
    "@oclif/plugin-not-found 3.2.68 (core)",
    "@oclif/plugin-plugins 5.4.47 (core)",
    "@oclif/plugin-search 1.2.31 (core)",
    "@oclif/plugin-update 4.7.7 (core)",
    "@oclif/plugin-version 2.2.33 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.48 (core)",
    "@oclif/plugin-which 3.2.40 (core)",
    "@salesforce/cli 2.108.6 (core)",
    "agent 1.24.13 (core)",
    "apex 3.8.1 (core)",
    "api 1.3.3 (core)",
    "auth 3.9.8 (core)",
    "code-analyzer 5.0.0 (user) published 163 days ago (Tue Apr 29 2025) (latest is 5.5.0)",
    "community 3.3.19 (user) published 180 days ago (Sat Apr 12 2025) (latest is 3.3.41)",
    "data 4.0.57 (core)",
    "deploy-retrieve 3.23.3 (core)",
    "info 3.4.88 (core)",
    "limits 3.3.67 (core)",
    "marketplace 1.3.8 (core)",
    "org 5.9.30 (core)",
    "packaging 2.20.5 (core)",
    "schema 3.3.82 (core)",
    "settings 2.4.48 (core)",
    "sobject 1.4.73 (core)",
    "telemetry 3.6.57 (core)",
    "templates 56.3.65 (core)",
    "trust 3.7.113 (core)",
    "user 3.6.38 (core)"
  ]
}

**Comment by thesunlover** [comment]
+1
I also got the same error in latest version. I observe it since 2.107.6, 2.108.6
I use sf cli with the global npm scope.

**Comment by thesunlover** [comment]
This issue has been fixed in apex-plugin v3.8.3...
I have resolved this for myself by using ```sf plugins install apex@3.8.3```

**Comment by matthew-zolp** [comment]
As of today, still experiencing this error when trying to specify a test suite on v2.108.6

**Comment by thesunlover** [comment]
The fix is not included in that version of sf cli, but the apex-plug-in

**Comment by matthew-zolp** [comment]
> The fix is not included in that version of sf cli, but the apex-plug-in

@thesunlover I'd still consider this unresolved, since our CI pipeline should be able to run this command with the sf cli only as it did before.

**Comment by thesunlover** [comment]
> > The fix is not included in that version of sf cli, but the apex-plug-in
> 
> [@thesunlover](https://github.com/thesunlover) I'd still consider this unresolved, since our CI pipeline should be able to run this 

Completely agree about the status as unresolved. it is not included in the latest version 2.108.6. Just wanted to state the options:

- you can add to your CI/CD instruction to upgrade the plugin (`sf plugins install apex@3.8.3`)
- rollback to 2.106.6 where this is not broken

**Comment by cristiand391** [comment]
this should be fixed in latest release (v2.111.7)
