### ISSUE TITLE
Suddenly getting "The query result is missing 10000 records due to a 10,000 limit for performance reasons..." message repeatedly in stderr

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#554]
After updating the CLI, I'm suddenly getting the following when running `force:source:pull`:

```
sfdx force:source:pull
(node:18156) Warning: The query result is missing 10000 records due to a 10,000 limit for performance reasons. Increase the number of records returned by setting the config value "maxQueryLimit" or the environment variable "SFDX_MAX_QUERY_LIMIT" to 10000 or greater than 10,000.
(node:18156) Warning: The query result is missing 10000 records due to a 10,000 limit for performance reasons. Increase the number of records returned by setting the config value "maxQueryLimit" or the environment variable "SFDX_MAX_QUERY_LIMIT" to 10000 or greater than 10,000.
(node:18156) Warning: The query result is missing 10000 records due to a 10,000 limit for performance reasons. Increase the number of records returned by setting the config value "maxQueryLimit" or the environment variable "SFDX_MAX_QUERY_LIMIT" to 10000 or greater than 10,000.
=== Pulled Source
No results found
```

Is that intentional? My guess is that it's not, but if it is, should all users start to specify that environment variable?

**Comment by amphro** [comment]
That was not intentional. It is supposed to only show up if there are actual missing records for anything using the autofetch method. This *should* never show up for archive installs and only on NPM installs if you updated just at the right time. We patched in https://github.com/forcedotcom/sfdx-core/pull/270/files and https://github.com/forcedotcom/sfdx-core/pull/268 so it shouldn't happen anymore. FYI @WillieRuemmele 

However, a `npm install sfdx-cli` might not fix this if you already have it installed because of the way module resolution works. So an uninstall and install might be required.

Please reopen if you verified it is still being thrown from the lastest version of `@salesforce/core`.

**Comment by SCWells72** [comment]
@amphro when was that fix put into place? I did a full uninstall/reinstall about an hour ago due to some other issues I was having. I can do another one if the fix is more recent than that, or if you'd like me to check again just for posterity.

**Comment by amphro** [comment]
It should be older than that. How did you install?

**Comment by SCWells72** [comment]
@amphro I downloaded the Windows 64 installer from https://developer.salesforce.com/tools/sfdxcli and installed it.

**Comment by amphro** [comment]
Ok that is super odd. Let me see if the new installer for Thursday's release will fix it.

**Comment by tfuda** [comment]
FYI, I concur this is still happening. I also just uninstalled/reinstalled using the Windows 64 bit installer and I'm getting this warning.

**Comment by dieffrei** [comment]
Same error today! MACOSX

**Comment by AllanOricil** [comment]
Oh yes. I have it too. I opened a feature request to remove it #557

**Comment by efortenberry** [comment]
I'm getting the same warning message every time I run sfdx force:source:push or pull

**Comment by eshupps** [comment]
Seeing the same error as well running sfdx force:source:push. It was working fine last week, today created a new scratch org and cannot push any code.

**Comment by amphro** [comment]
Sorry everyone, the way that warning is being shown was a bug we fixed in a child library. We thought we fixed it before it got fixed before bundled with the CLI but that doesn't appear to be the case. It should be fixed this Thursday's release. It doesn't actually have any impact on your commands other than being annoying.  

> It was working fine last week, today created a new scratch org and cannot push any code.
@eshupps that is most likely a different problem. This is just a warning (and invalid at that) and not an actual error.

**Comment by annesunilreddy** [comment]
I am seeing the same errors. Thanks for the info and update @amphro,

**Comment by SCWells72** [comment]
FYI, I just updated to today's build (on Windows) and it seems fixed now.

**Comment by pquintairos** [comment]
FYI I'm still seeing this issue on `sfdx-cli/7.105.0 wsl-x64 node-v16.3.0`
And I can also see it happening on my pipeline when using the docker image `salesforce/salesforcedx:latest-slim`
```
p@LAPTOP:~$ sfdx force:data:soql:query -q "SELECT count() FROM ApexClass WHERE Name like '%Test%'" -t --json
(node:7253) Warning: The query result is missing 205 records due to a 20000 record limit. Increase the number of records returned by setting the config value "maxQueryLimit" or the environment variable "SFDX_MAX_QUERY_LIMIT" to 205 or greater than 20000.
(Use `node --trace-warnings ...` to show where the warning was created)
{
  "status": 0,
  "result": {
    "done": true,
    "totalSize": 205,
    "records": []
  }
}
```
