### ISSUE TITLE
force:source:pull isn't retrieving custom labels

### ISSUE THREAD

**Issue by ilanbalink** [forcedotcom/cli#600]
### Summary

pull isn't retrieving new labels or updated changed

### Steps To Reproduce:

1.  in a scratch org, create a new label
2. do sfdx force:source:pull

### Expected result
the new added label should be retrieved in the labels\Custom_Labels file

### Actual result
Nothing was retrieved
_Describe what actually happened instead_.
Nothing was retrieved
### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.73.2-feef087df8 win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.2 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.9.2
├─ templates 49.4.4
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ apex 0.0.9
├─ salesforce-alm 49.10.0
└─ custom-metadata 1.0.8
sfdx-cli 7.73.2 (core)

**OS and version**:
WINDOWS 10

**Comment by ilanbalink** [comment]
![Annotation 2020-09-08 082733](https://user-images.githubusercontent.com/33839840/92436416-48214e80-f1ad-11ea-9260-822dba0f4da4.png)

**Comment by jflowers45** [comment]
I am having this issue as well.

**Comment by mcsollinger** [comment]
I am having this issue as well. MacOS, CLI version 7.74.1

**Comment by ricofairsailcom** [comment]
same in sfdx-cli/7.75.1 for windows

**Comment by JulienGaiotto** [comment]
Are yall sure that "Protected Component" on your labels is unchecked ?
It seems that checkbox is true by default.

I had the same issue, went to my label, clicked edit, unchecked the "Protected Component" checkbox, and managed to pull my label in my project folder.

Hope that helps.

**Comment by ricofairsailcom** [comment]
Hi @jgaiotto, 
My 435 custom labels have the Protected Component checked, it was working fine until now.

**Comment by sumugapadman** [comment]
+1 

I have the same issue. Even after unchecking the "**Protected Component**" `sfdx force:source:pull` did not yield results . 
And the package.xml did not work as well. `sfdx force:source:retrieve -x manifest/package.xml`
Had to manually retrieve it and add it to my custom labels file.

**Comment by shetzel** [comment]
I added a fix for pulling custom labels in the current release candidate. Can you try installing that to see if it unblocks you?
sfdx plugins:install salesforcedx@latest-rc

Related to #673

**Comment by clairebianchi** [comment]
This is fixed

**Comment by raviduttsharma** [comment]
Does not seem to be fixed. I am on sfdx-cli/7.82.0-3d0c527ac6 darwin-x64 node-v12.18.3, and still facing this issue.

**Comment by ayan-sarkar-cse** [comment]
Try using SFDX retrieve command
sfdx force:source:retrieve -p force-app/main/default/labels

**Comment by shetzel** [comment]
@raviduttsharma - make sure your plugins are on the core versions.  `sfdx plugins --core` should output `(core)` next to the salesforcedx version.  If it doesn't, run `sfdx plugins:uninstall salesforcedx` to get back on the core version.
