### ISSUE TITLE
Unable to force:source:deploy a project containing Email and Report Folders using package.xml

### ISSUE THREAD

**Issue by daveespo** [forcedotcom/cli#612]
### Summary

I have a project in source format. I am able to push the source tree to a scratch org using `force:source:push` but when I try to deploy to a DE org using a `package.xml` manifest, I get the following error:

```
Job ID | 0Af1F00001NYnX6SAL
SOURCE PROGRESS | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 0/2 Components
TYPE   PROJECT PATH  PROBLEM
─────  ────────────  ──────────────────────────────────────
Error  N/A           Cannot find folder:ExampleReportFolder
Error  N/A           Cannot find folder:ExampleEmailFolder
ERROR running force:source:deploy:  Deploy failed.
```

This sounds similar to #609 

### Steps To Reproduce:

**Repository to reproduce:** 

https://github.com/patronmanager/folder.creation.bug.2020-09

 * Clone the above repo
 * Create an org (scratch org or DE org will both work)
 * Deploy using package.xml deployment: `sfdx force:source:deploy -x mdapi/package.xml`
 * Expected: Successful deployment of the Email Template and Report nested in the appropriate folder
 * Actual: The error documented above

### Additional information

sfdx-cli/7.74.1-32db2396ed win32-x64 node-v12.18.3

sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
etcopydata 0.5.12-b (beta)
generator 1.1.3 (core)
salesforcedx 49.10.0 (core)
├─ salesforce-alm 49.11.0 (core)
├─ apex 0.0.9 (core)
├─ templates 49.4.4 (core)
├─ custom-metadata 1.0.10 (core)
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
sfdx-cli 7.74.1 (core)

**Comment by shetzel** [comment]
Yeah, I bet this an issue in the convert for folder types.  We'll fix.

**Comment by vnehess** [comment]
I am seeing this issue in the latest sdfx version:

salesforcedx 50.1.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ templates 50.1.0 (core)
├─ custom-metadata 1.0.10 (core)
├─ apex 0.1.1 (core)
└─ salesforce-alm 50.1.1 (core)
sfdx-cli 7.76.1 (core)

**Comment by shetzel** [comment]
This is specific to EmailTemplate and EmailFolder.  Documents, Reports, and Dashboards should work due to the conventions those types follow.  Release ETA is salesforcedx v50.4.0.

**Comment by shetzel** [comment]
This is fixed in: salesforcedx v50.5.0 (November 12, 2020) - CLI 7.80.0

**Comment by edralph** [comment]
I've noticed that if Classic Email Templates are created in the 'Unfiled Public Folder' then they push/pull to scratch orgs fine, but they don't deploy to a packaging org.  There is no deployment error, they just don't appear in the package components (but it does appear in package.xml).

If you create a new Email Template Folder, and put the email template in that newly created folder, then it does deploy to the package as you would expect.

I'm running v50.5.0

**Comment by iandrosov** [comment]
This seems still an issue in the new version sfdx 7.84.2-a2868a68d5 Cannot find folder:<Email template folder name>

**Comment by emregunel** [comment]
Having the same issue here. sfdx-cli/7.84.2-a2868a68d5

**Comment by lily-yu1** [comment]
same issue here sfdx-cli/7.94.3-a4e7c7955b

**Comment by chernyy-svyat** [comment]
same issue in sfdx-cli/7.97.1 darwin-x64 node-v14.15.5

**Comment by nvuillam** [comment]
Issue is back in latest sfdx-cli version, report, email and documents juste contain folder metadatas but none of the folder items, leading to a force:source:deploy error :/

**Comment by nvuillam** [comment]
@iandrosov @emregunel @lily-yu1 @chernyy-svyat  did you find a workaround ?

Command:

`MD_API_TEMP_FOLDER=./tmp/ sfdx force:source:convert -x manifest/package.xml`

My package.xml contains:

```xml
  <types>
    <members>ADMINISTRATIFAssistantesAdmin</members>
    <members>ADMINISTRATIFAssistantesAdmin/Contratsclients</members>
    <members>ADMINISTRATIFAssistantesAdmin/Contratsclients/Date_dbut_contrat_Appli_Mois_M_et_M1_ilK</members>
    <members>ADMINISTRATIFAssistantesAdmin/Contratsclients/Echance_Contrat_Cadre_cek</members>
    <members>ADMINISTRATIFAssistantesAdmin/Contratsclients/Nouveau_rapport_FM1</members>
    <members>ADMINISTRATIFAssistantesAdmin/Divers</members>
    <members>ADMINISTRATIFAssistantesAdmin/Divers/Interco_France_M4x</members>
    <members>ADMINISTRATIFAssistantesAdmin/Divers/Suivi_Montant_garantie_Hhr</members>
    <members>ADMINISTRATIFAssistantesAdmin/Facture</members>
    <members>ADMINISTRATIFAssistantesAdmin/Facture/clients_en_irrgularit_DsY</members>
    <members>ADMINISTRATIFAssistantesAdmin/Soustraitants</members>
    <members>ADMINISTRATIFAssistantesAdmin/Soustraitants/Contrat_ST_Fin_ce_moisci_dUJ</members>
    <members>ADMINISTRATIFAssistantesAdmin/Soustraitants/Contrat_ST_Fin_mois_prochain_CnH</members>
    <members>COMMERCIALBusinessDevelopper</members>
    <members>COMMERCIALBusinessDevelopper/Prvisionnel</members>
    <members>COMMERCIALBusinessDevelopper/Prvisionnel/CAannuel</members>
    <members>COMMERCIALBusinessDevelopper/Prvisionnel/Marge_annuelle_GHj</members>
    <members>COMMERCIALBusinessDevelopper/Prvisionnel/TJM_Affectation_actives_cnN</members>
    <name>Report</name>
  </types>
```

My report folder contains the reports and the report folders metadata
![image](https://user-images.githubusercontent.com/17500430/133237349-4772d62a-cf3b-4b3f-bccd-39f4684ec2a8.png)

Result in MD_API_TEMP_DIR (only the 2 root folders)

![image](https://user-images.githubusercontent.com/17500430/133237724-fb834ffb-61db-426f-864c-8d9390b2a828.png)

So obviously Deploy result:
![image](https://user-images.githubusercontent.com/17500430/133237601-efa40c7a-22c0-4f2e-be03-3139a23d7039.png)

**Comment by daveespo** [comment]
@nvuillam -- it looks like you're seeing #1165

**Comment by nvuillam** [comment]
@daveespo indeed... i have a go live next week, cross fingers ...
The issue is in forcedotcom/sourcedeployretrieve that filters folders and reports within them, but i've not gotten deep enough yet with breakpoints to find a solution :/
