### ISSUE TITLE
Can't Update - Error: HTTP 403: Invalid channel stable

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#788]
### Summary
Can't Update sfdx - HTTP 403: Invalid channel stable

![image](https://user-images.githubusercontent.com/55927613/104093154-955b1d00-5280-11eb-831a-ddc813a1b5a4.png)

### Steps To Reproduce:
No idea. The update command never failed with this error message.

### Expected result

sfdx update should update the cli or a least tell exactly what is the problem.

### Actual result

sfdx update returns 

Error: HTTP 403: Invalid channel stable

### Additional information

**SFDX CLI Version**: 7.81.0 linux-arm64 node-v14.15.0
**OS and version**: Ubuntu 20

**Comment by AllanOricil** [comment]
Could this be related?
https://github.com/forcedotcom/cli/issues/389

**Comment by shetzel** [comment]
@AllanOricil - Thanks for reporting.  Can you please try again and close this issue if it works for you?  I believe I just fixed it.

**Comment by AllanOricil** [comment]
@shetzel the error is still happening

![image](https://user-images.githubusercontent.com/55927613/104135182-4eefe600-5386-11eb-9554-bd2abc47b544.png)

**Comment by amphro** [comment]
@AllanOricil can you run with `--dev-debug`? More specifically I want to know what URL it is failing on. Can you access https://developer.salesforce.com/media/salesforce-cli/manifest.json from your terminal?

**Comment by AllanOricil** [comment]
Here is the output. Maybe your service is blocking because of the user agent?
![image](https://user-images.githubusercontent.com/55927613/104528665-c9776a80-55ff-11eb-8c63-3616282dc29c.png)
![image](https://user-images.githubusercontent.com/55927613/104528417-1b6bc080-55ff-11eb-9800-be90b07cb826.png)

And I can access that json from the url
![image](https://user-images.githubusercontent.com/55927613/104528514-6b4a8780-55ff-11eb-87a4-2e055bb4ac49.png)

I also noticed that I can't perform Web OAuth flow from that machine. It might be related. After entering the login credentials it stays loading forever a link. And when I refresh that link it says that an error happened.

**Comment by mrichmon12** [comment]
I'm also having this exact problem but from WSL. I actually uninstalled WSL and started from scratch only to run into the issue again. Here is the error from the debug output.

![image](https://user-images.githubusercontent.com/2294048/104530653-6cb58900-55da-11eb-8a48-d713380aa0ba.png)

**Comment by mrichmon12** [comment]
So it looks like wsl-x64 and linux-arm64 are platforms that are not available in the manifest.json file. Does this means these platforms are no longer supported? I've been using the CLI on WSL for quite a long time without any problems.

Here is another issue with the same underlying problem: #610

**Comment by AllanOricil** [comment]
> So it looks like wsl-x64 and linux-arm64 are platforms that are not available in the manifest.json file. Does this means these platforms are no longer supported? I've been using the CLI on WSL for quite a long time without any problems.

I think they are just missing. Because sfdx is based on Oclif which is written for Node which supports these platforms.

**Comment by mrichmon12** [comment]
@AllanOricil were you able to get Web OAuth flow to work at all? That is my main issue right now. Appears to overlap with #783. I'll try the workaround suggested there.

**Comment by AllanOricil** [comment]
> @AllanOricil were you able to get Web OAuth flow to work at all? That is my main issue right now. Appears to overlap with #783. I'll try the workaround suggested there.

No :/

**Comment by mrichmon12** [comment]
So I moved over to the npm installation method, but the latest version of the CLI also fails to successfully web auth there as well. Downgrading to 7.76.0 seemed to do the trick.

**Comment by AllanOricil** [comment]
> So I moved over to the npm installation method, but the latest version of the CLI also fails to successfully web auth there as well. Downgrading to 7.76.0 seemed to do the trick.

@mrichmon12  How did you uninstalled the binary? Im not that familiar with linux commands yet haha

**Comment by AllanOricil** [comment]
@amphro  @mrichmon12 I solved my problem uninstalling sfdx-cli completly and installing it again with npm.
I followed this [tutorial](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm#:~:text=Select%20Start%20%3E%20Control%20Panel%20%3E%20Programs,your%20home%20directory%2C%20delete%20the%20.)

![image](https://user-images.githubusercontent.com/55927613/104658350-7e6e5d80-56ba-11eb-8716-1224b6d24556.png)


But

I can't run the update command. It still outputs the same error message

![image](https://user-images.githubusercontent.com/55927613/104658418-a8278480-56ba-11eb-9d68-33fb0efe7ce3.png)

**Comment by mrichmon12** [comment]
> I can't run the update command. It still outputs the same error message

@AllanOricil As per the [Salesforce CLI Setup Guide](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm), when installed via npm you should use `npm install --global sfdx-cli` to update.

If you are looking for a specific version you can specify the version number as well (e.g.: `npm install --global sfdx-cli@7.76.0`)

When I downgraded to 7.76.0 my OAuth issues were resolved.

**Comment by amphro** [comment]
The `sfdx update` doesn't work for npm installs and will output why. The fact that you are still getting that error @AllanOricil implies that it is still running the installer version. What is the output of `which sfdx`?

**Comment by AllanOricil** [comment]
> The `sfdx update` doesn't work for npm installs and will output why. The fact that you are still getting that error @AllanOricil implies that it is still running the installer version. What is the output of `which sfdx`?

@amphro I made sure to have everything uninstalled before installing again with npm. It is running the npm "version".

![image](https://user-images.githubusercontent.com/55927613/104662918-b6c66980-56c3-11eb-93f3-b8faead3bd24.png)

**Comment by mrichmon12** [comment]
It looks like it must be checking the manifest before indicating it should be updated using npm?
```
~ sfdx update                                                                                                                                                                                                                 
sfdx-cli: Updating CLI... !
    Error: HTTP 403: Invalid channel stable
~ which sfdx                                                                                                                                                                                                                
/home/mrichmond/.nvm/versions/node/v14.15.4/bin/sfdx
```

**Comment by amphro** [comment]
That is odd. The right way to update an npm installed version is to use npm.

I see it is checking the channel then outputting the message:

```
➜ sfdx update
https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/darwin-x64
{
  version: '7.84.2-a2868a68d5',
  channel: 'stable',
  sha256gz: 'f4b3b318f04b3abdb03f2e13419a0d093ccb94d33b15d174fdf0f0683f629069',
  sha256xz: '67e8eda6613350f39b5d700d84ab3e6ef0c3b95f758197de5bf99d3a4d08b3af',
  node: { compatible: '>=8.10.0', recommended: '12.18.3' }
}
 ›   Warning: Use "npm update --global sfdx-cli" to update npm-based installations.
sfdx-cli: Updating CLI... not updatable
sfdx-cli: Updating plugins... done
```

Can you run with `--dev-debug`?

**Comment by amphro** [comment]
Can

**Comment by AllanOricil** [comment]
@amphro I can't auth to any org when using sfdx from a raspbery pi. Could this be related somehow? Basically every time I try to auth the browser just keeps loading  and nothing happens.

**Comment by mshanemc** [comment]
I think the auth thing is related to https://github.com/forcedotcom/cli/issues/881 which was bothering win/linux for a while earlier this year.  It's fixed on recent releases--what's running on the pi?

**Comment by AllanOricil** [comment]
This issue is fixed and I was able to auth to an org on the pi. Thank you. I just had to uninstall sfdx, and then install it again (v7.94)

**Comment by deshartman** [comment]
Seems it is back again

twilio update --dev-debug
 » MORE INFO: https://twil.io/cli
twilio-cli: Updating CLI... !
    Error: HTTP 403: Invalid channel --dev-debug

**Comment by cristiand391** [comment]
@deshartman you should file an issue in the Twilio CLI repo.

**Comment by AllanOricil** [comment]
> @deshartman you should file an issue in the Twilio CLI repo.

🔥
