### ISSUE TITLE
Data Tree Export Not Returning Results

### ISSUE THREAD

**Issue by robertStrunk** [forcedotcom/cli#828]
## Summary
A valid query that should return results will not return results when "sfdx force:data:tree:export" is called with a --query flag

## Steps To Reproduce:
1. Create a .soql file with a query that is filtering on the Id field. My example below:
`
SELECT  Name
FROM   Product2 
WHERE Id IN (
    '01t1X000005P61TQAS',
    '01t1X0000062jnyQAA',
    '01t0J00000F4ItSQAV',
    '01t1X000005P6vXQAS',
    '01t5I000000AS28QAG',
    '01t1X000005P7HdQAK',
    '01t1X0000062uXeQAI'
)`
2. Use the sfdx force:data:tree:export command with the query flag. My example below:
`
sfdx force:data:tree:export --query scripts/soql/try2.soql --prefix omnichannelBundle --outputdir data/omnichannelBundle --plan -u WP_nDev --json
`

## Expected result

Query should have returned results (That exact query copy pasted into other tools will return results)

## Actual result

Query returned zero results

## Additional information

This is only happening when I filter on the Id field trying to match it with the list of Ids. If I use the list of Ids to exclude from the results then it will return some results. I also tried it with a different text field and it worked fine. Examples below:

### This Works (notice the "NOT IN")
`
SELECT  Name
FROM   Product2 
WHERE Id NOT IN (
    '01t1X000005P61TQAS',
    '01t1X0000062jnyQAA',
    '01t0J00000F4ItSQAV',
    '01t1X000005P6vXQAS',
    '01t5I000000AS28QAG',
    '01t1X000005P7HdQAK',
    '01t1X0000062uXeQAI'
)`

### This Works (changed to Name field)
`
SELECT  Name
FROM   Product2 
WHERE Name IN (
    'product_1',
    'product_2',
    'product_3',
    'product_4'
)`

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
`sfdx-cli/7.84.2-a2868a68d5 win32-x64 node-v12.18.3`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.6 (core)
config 1.2.3 (core)
generator 1.1.3 (core)
salesforcedx 50.13.3 (core)
├─ user 1.0.5 (core)
├─ schema 1.0.3 (core)
├─ limits 1.0.2 (core)
├─ templates 50.4.0 (core)
├─ salesforce-alm 50.13.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.11 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.84.2 (core)
```

**OS and version**:
OS Name: `Microsoft Windows 10 Enterprise`
OS Version: `10.0.17763 Build 17763`

**Comment by WillieRuemmele** [comment]
Hi @robertStrunk thanks for such a detailed issue. Would you mind trying this command with the beta `data` plugin? If you could run `sfdx plugins:install data` and accept that it is currently unsigned and try running your command again that would be fantastic. You would then run `sfdx plugins:uninstall data` to revert

if it fails with the beta version could you add `--dev-debug` to the command and paste the output here?

**Comment by robertStrunk** [comment]
As requested. 
The url in Line 368 stands out. (I cleansed the domain name so please ignore the XXXXXX.my.salesforce.com)
[dump.txt](https://github.com/forcedotcom/cli/files/5896129/dump.txt)

**Comment by WillieRuemmele** [comment]
Thanks @robertStrunk! Just to verify, does that query return data when executed with `sfdx force:data:soql:query`? Just want to make sure

**Comment by robertStrunk** [comment]
@WillieRuemmele  Looks like the force:data:soql:query is returning results. It's worth noting that that command doesn't support calling a .soql file (to my knowledge anyway) so I had to add the query inline as opposed to the path to the file. Here is a copy paste of the command that did return the desired results. 
`sfdx force:data:soql:query -u WP_nDev -q "SELECT Name FROM Product2 WHERE Id IN ('01t1X000005P61TQAS','01t1X0000062jnyQAA','01t0J00000F4ItSQAV','01t1X000005P6vXQAS','01t5I000000AS28QAG','01t1X000005P7HdQAK','01t1X0000062uXeQAI')"`

**Comment by WillieRuemmele** [comment]
thanks for your help @robertStrunk we'll file this as a bug and get on it

**Comment by robertStrunk** [comment]
@WillieRuemmele  I believe I know the cause and have a guess at the fix. Looks like the query is being transformed to be all lower case including the ids that are being passed in. If you look at the query in the URL on line 368 of the dump I provided you should be able to see the query that is all lower case. So I assume the way to resolve this issue would be to update the `force:data:tree:export` code to not use a string.toLowerCase() on the query that is passed in.

The query as typed in my soql file:
`FROM Product2 
WHERE Id IN (
    '01t1X000005P61TQAS',
    '01t1X0000062jnyQAA',
    '01t0J00000F4ItSQAV',
    '01t1X000005P6vXQAS',
    '01t5I000000AS28QAG',
    '01t1X000005P7HdQAK',
    '01t1X0000062uXeQAI'
)`

The query after it is processed by the force:data:tree:export code:
`  sfdx:ExportApi DEBUG Processed 0 records from query: select  name
  sfdx:ExportApi from    product2
  sfdx:ExportApi where   id in (
  sfdx:ExportApi     '01t1x000005p61tqas',
  sfdx:ExportApi     '01t1x0000062jnyqaa',
  sfdx:ExportApi     '01t0j00000f4itsqav',
  sfdx:ExportApi     '01t1x000005p6vxqas',
  sfdx:ExportApi     '01t5i000000as28qag',
  sfdx:ExportApi     '01t1x000005p7hdqak',
  sfdx:ExportApi     '01t1x0000062uxeqai'
  sfdx:ExportApi ) +1ms`

**Comment by WillieRuemmele** [comment]
Wow, great detective work. I'll take a look and see why that's happening. That's one of our new OSS repos, you can see where/why it's doing it here https://github.com/salesforcecli/data/blob/0ac477e3dcad5c4bf61f4e85b131b05c37d6af37/packages/plugin-data/src/api/data/tree/exportApi.ts#L118 I'll fix it. just pretty cool to see!

**Comment by robertStrunk** [comment]
Thanks for sharing that! I tried to find it earlier but am not too familiar with your repos.

**Comment by WillieRuemmele** [comment]
Hi @robertStrunk check out the [announcement](https://github.com/forcedotcom/cli/issues/907) for the new [data](https://github.com/forcedotcom/cli/issues/907) plugin

**Comment by mshanemc** [comment]
I think this is fixed in the new data plugin released 4/1.  If not, re-open or create a new case.

**Comment by thedgglmister** [comment]
@WillieRuemmele I'm still seeing this issue, even after installing the new plugin. Can see that the query, including Ids, are being transformed to all lower case.

**Comment by WillieRuemmele** [comment]
Hi @thedgglmister just to confirm you're on `plugin-data` version `0.6.0`? can I see the output of `sfdx plugins --core`?

**Comment by thedgglmister** [comment]
@WillieRuemmele Correct, I'm on `0.6.0`. Output of `sfdx plugins --core`:
```
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
auth 1.7.1 (core)
config 1.2.13 (core)
data 0.6.0
generator 1.1.7 (core)
salesforcedx 52.0.0 (latest-rc)
├─ apex 0.2.2
├─ custom-metadata 1.0.12
├─ org 1.6.6
├─ limits 1.2.1
├─ schema 1.0.7
├─ templates 51.5.0
├─ user 1.3.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
└─ salesforce-alm 52.0.0
sfdx-browserforce-plugin 2.6.3
sfdx-cli 7.110.0 (core)
sfdx-wry-plugin 0.0.11 (link) /Users/iremongb/sfdx-wry-plugin/utils/sfdx-wry-plugin
telemetry 1.2.2 (core)
```

**Comment by justin-lyon** [comment]
sfdx-cli/7.150.0 darwin-arm64 node-v18.1.0

This is still an issue with force:data:tree:export

```
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.3.1 (core)
@oclif/plugin-not-found 1.2.6 (core)
@oclif/plugin-plugins 1.10.11 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.4 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 2.0.0 (core)
apex 0.11.0 (core)
auth 2.0.2 (core)
community 1.1.4 (core)
config 1.4.6 (core)
custom-metadata 1.1.0 (core)
data 0.6.15 (core)
generator 2.0.0 (core)
info 2.0.0 (core)
limits 2.0.0 (core)
org 1.12.1 (core)
salesforce-alm 54.3.0 (core)
schema 2.1.0 (core)
sfdx-cli 7.150.0 (core)
signups 1.0.0 (core)
source 1.9.7 (core)
telemetry 1.4.0 (core)
templates 54.6.0 (core)
trust 1.1.0 (core)
user 1.7.1 (core)
```

**Comment by WillieRuemmele** [comment]
Hey @justin-lyon 👋 

Can you try upgrading the CLI to the latest release and giving it another go?

**Comment by justin-lyon** [comment]
Getting the same error still.

```
sfdx-cli/7.154.0 darwin-arm64 node-v18.1.0

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.3.1 (core)
@oclif/plugin-not-found 1.2.6 (core)
@oclif/plugin-plugins 1.10.11 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.4 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 2.0.1 (core)
apex 0.13.0 (core)
auth 2.0.3 (core)
community 2.0.0 (core)
config 1.4.11 (core)
custom-metadata 1.1.0 (core)
data 2.0.3
generator 2.0.1 (core)
info 2.0.1 (core)
limits 2.0.1 (core)
org 1.13.2 (core)
salesforce-alm 54.4.0 (core)
schema 2.1.1 (core)
sfdx-cli 7.154.0 (core)
signups 1.1.2 (core)
source 1.10.2 (core)
telemetry 2.0.0 (core)
templates 54.8.0 (core)
trust 2.0.1 (core)
user 2.0.2 (core)
```

```sql
-- scripts/soql/testing.sql
SELECT Id
FROM Account
WHERE Id = '0015f000003sTipAAE'
```

```
$ sfdx force:data:tree:export -q scripts/soql/testing.sql
Query returned no results
--------------------------------------------------------------------------------
$ sfdx force:data:soql:query --json -q "$(cat scripts/soql/testing.sql)"
{
  "status": 0,
  "result": {
    "totalSize": 1,
    "done": true,
    "records": [
      {
        "attributes": {
          "type": "Account",
          "url": "/services/data/v54.0/sobjects/Account/0015f000003sTipAAE"
        },
        "Id": "0015f000003sTipAAE"
      }
    ]
  }
}
```
