### ISSUE TITLE
sfdx force:source:delete does not work on production orgs

### ISSUE THREAD

**Issue by BalajiKshatriy** [forcedotcom/cli#971]
force:source:delete fails and wouldn't run on production orgs. 

### Steps to Reproduce:

- Connect to any production org and attempt to delete any metadata (in this case attempting to delete a custom field)

`sfdx force:source:delete -m "CustomField:testobject__c.Admin_Badges__c"
`

throws error:
{
  "status": 1,
  "name": **"sf:INVALID_OPERATION",**
  "message": "INVALID_OPERATION: **testLevel of NoTestRun cannot be used in production organizations**",
  "exitCode": 1,
  "commandName": "SourceDeleteCommand"
}

- As above command failed with testLevel missing error, try providing testlevel and attempt the delete

`sfdx force:source:delete -m "CustomField:trailheadapp__Trailhead_User_Data__c.Admin_Badges__c" -l RunLocalTests
`

throws error:
{
  "status": 1,
  "name": "Error",
  "message": **"Unexpected arguments: -l, RunLocalTests\nSee more help with --help",**
  "exitCode": 1,
  "commandName": "SourceDeleteCommand",
  "stack": "Error: Unexpected arguments: -l, RunLocalTests
}

tried other possibilities with --checkonly flag etc.. but none help.
tried with latest and greatest cli & plugin version.

### Couple other notes:

1. The [documentation from Salesforce ](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source)is very Vague around this and needs correction as well. It doesn't clearly state whether this is designed to work for production orgs or not.
2. This command should also take manifest file (package.xml/destructivechanges.xml) to have scalable way to list components to delete. currently it seem like designed to accept only comma separated metadata components which is not viable.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9137776](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000Asb9YAC/view)

**Comment by fransf-wtax** [comment]
@forcedotcom Any update here? We don't have visibility on work items.

**Comment by shetzel** [comment]
@fransf-wtax - We first want to promote the source plugin to the production CLI core plugins.  Once that work is complete the next scheduled work will be to add the source delete command to it, but also to support destructive changes as part of a source:deploy.  My guess is it will be delivered in late July or early August.

**Comment by cristiand391** [comment]
This was fixed in latest v7.120.0, release notes:
https://github.com/forcedotcom/cli/tree/main/releasenotes#71200-sept-30-2021

**Comment by cnwork** [comment]
> This was fixed in latest v7.120.0, release notes: https://github.com/forcedotcom/cli/tree/main/releasenotes#71200-sept-30-2021

Sorry but this still seems to be happening even in the latest release. 
Here's my output running  `sfdx -v`
`sfdx-cli/7.132.0 wsl-x64 node-v16.13.0`

And command with error:
`sfdx force:source:delete --sourcepath /home/user/workspace/work/NewProject/Gaming/force-app/main/default/classes/SupportVFTemplateController.cls --noprompt
*** Deleting with SOAP API ***
ERROR running force:source:delete:  INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations`

**Comment by mariomvp11** [comment]
> This was fixed in latest v7.120.0, release notes: https://github.com/forcedotcom/cli/tree/main/releasenotes#71200-sept-30-2021

The error remain unresolved in the latest release:
`sfdx-cli/7.201.6 win32-x64 node-v18.15.0`

Error:
`sfdx force:source:delete --sourcepath c:\Users\mario\Desktop\Workspace\SF Albira PRO\force-app\main\default\lwc\gtagManagerScript --noprompt
(node:9344) Warning: Deprecated environment variable: SFDX_JSON_TO_STDOUT. Please use SF_JSON_TO_STDOUT instead.
(Use `node --trace-warnings ...` to show where the warning was created)
Warning: The "force source delete" command has been deprecated. Use "project delete source" instead.
Warning: The "--sourcepath" flag has been deprecated. Use "--source-dir | -p" instead.
Warning: The "--noprompt" flag has been deprecated. Use "--no-prompt | -r" instead.
*** Deleting with SOAP API ***
Error (1): INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations`
